Repository kaskada-ai/kaskada, pull requests merged in 2023-04, with the labels that each got.

#203 Add an "examples" section to the docs with links to our notebooks
  docs-src/modules/ROOT/nav.adoc
  examples/Kaskada with CSV.ipynb
  examples/ML_example.ipynb
  examples/Public Demo Examples.ipynb
  examples/Table Pulsar Source.ipynb
Labels: documentation

#204 Promote the subsections of "integrating with feature stores" to be top-level
  docs-src/modules/integrating/nav.adoc
  docs-src/modules/integrating/pages/apache-cassandra.adoc
  docs-src/modules/integrating/pages/apache-pulsar.adoc
  docs-src/modules/integrating/pages/aws-redshift.adoc
  docs-src/modules/integrating/pages/integrating-with-feature-stores.adoc
  docs-src/modules/integrating/pages/redis.adoc
  docs-src/modules/integrating/pages/snowflake.adoc
Labels: documentation

#144 feat: Add Object Store Crate to Engine
  Cargo.lock
  Cargo.toml
  crates/sparrow-main/src/serve.rs
  crates/sparrow-main/src/serve/compute_service.rs
  crates/sparrow-main/src/serve/file_service.rs
  crates/sparrow-runtime/Cargo.toml
  crates/sparrow-runtime/src/lib.rs
  crates/sparrow-runtime/src/metadata/raw_metadata.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/stores.rs
  crates/sparrow-runtime/src/stores/object_store_url.rs
  crates/sparrow-runtime/src/stores/object_stores.rs
  deny.toml
  tests/integration/docker-compose.s3.yml
  wren/compute/manager.go
Labels: enhancement, wren, sparrow

#207 (docs): Update hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#209 changed client-id log line to debug-level
  clients/cli/api/api.go
Labels: python

#212 (docs): Update hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#214 (tests): Enables integration tests including Pulsar
  .github/workflows/ci_engine.yml
  .github/workflows/reusable_ci_integration_tests.yml
  .github/workflows/reusable_ci_rust.yml
  .github/workflows/reusable_ci_wren.yml
  Dockerfile.integration
  Makefile
  run-integ.sh
  tests/integration/docker-compose-ci-integration.yml
Labels: build

#216 (tests): cleanup from PR #214
  .github/workflows/ci_engine.yml
  tests/integration/docker-compose-ci-integration.yml
Labels: build

#222 release engine 0.6.0, python client 1.3
  Cargo.lock
  Cargo.toml
  clients/python/pyproject.toml
  wren/.version
Labels: python, wren, sparrow

#225 Fix typo in faq.adoc
  docs-src/modules/overview/pages/faq.adoc
Labels: documentation

#224 (ci): adds python client release and publish to pypi via github workflow
  .github/workflows/release_python_client.yml
  clients/python/src/kaskada/api/session.py
  docs/release-process.adoc
  tests/integration/pythonClient/test_package.py
Labels: documentation, python, build

#226 Update labels to match visualization and sample code
  docs-src/modules/developing/pages/tables.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/overview/pages/what-is-kaskada.adoc
Labels: documentation

#230 Improvements from the first trial results
  clients/cli/api/api.go
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/developing/pages/materializations.adoc
  docs-src/modules/developing/pages/queries.adoc
  docs-src/modules/developing/pages/tables.adoc
  docs-src/modules/developing/pages/views.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
  docs-src/modules/getting-started/pages/index.adoc
Labels: documentation

#234 Updates from second trial
  clients/python/src/kaskada/api/session.py
  clients/python/src/kaskada/client.py
  docs-src/modules/ROOT/pages/installing.adoc
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/developing/pages/materializations.adoc
  docs-src/modules/developing/pages/queries.adoc
  docs-src/modules/developing/pages/slices.adoc
  docs-src/modules/developing/pages/tables.adoc
  docs-src/modules/developing/pages/views.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Labels: documentation, python

#238 Use the correct path syntax and highlight with bash
  clients/python/src/kaskada/client.py
  docs-src/modules/ROOT/pages/installing.adoc
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Labels: documentation, python

#237 (docs): config for readthedocs + deps for building docs
  .github/workflows/ci_engine.yml
  .readthedocs.yaml
  clients/python/docs/source/requirements.txt
  clients/python/src/kaskada/client.py
Labels: python, build

#243 removes quotes from version number in requirements.txt
  clients/python/docs/source/requirements.txt
Labels: python

#244 adds more required deps for docs
  clients/python/docs/source/requirements.txt
Labels: python

#246 (ci) workaround to allow python client workflow to be required
  .github/workflows/ci_client_python.yml
Labels: build

#245 (docs) adds extension to automatically call docs generate
  clients/python/docs/source/conf.py
  clients/python/docs/source/requirements.txt
  clients/python/poetry.lock
  clients/python/pyproject.toml
Labels: python

#213 changed last_publish_time to i64
  crates/sparrow-main/src/prepare.rs
  crates/sparrow-runtime/src/execute/pulsar_reader.rs
  crates/sparrow-runtime/src/prepare.rs
  proto/kaskada/kaskada/v1alpha/pulsar.proto
Labels: sparrow, proto

#261 (docs) RTD configuration
  clients/python/docs/source/.readthedocs.yaml
  clients/python/docs/source/conf.py
  clients/python/docs/source/index.rst
  deny.toml
Labels: python

#263 (docs) fixes link in docs -- deleting tables with cli
  docs-src/modules/developing/pages/tables.adoc
Labels: documentation

#264 (docs) updates link to deleting a table
  docs-src/modules/developing/pages/tables.adoc
Labels: documentation

#269 docs: Add example based on timeline presentation
  examples/timelines/kaskada_oss.ipynb
  examples/timelines/visualize.py
Labels: documentation

#265 (ci) include a build of the docs on each PR but do not publish
  .github/workflows/publish-antora-docs.yml
Labels: build

#271 Update docs to improve clarity and usability
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/developing/pages/queries.adoc
  docs-src/modules/developing/pages/tables.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Labels: documentation

#275 (docs) adds troubleshooting section and an entry for logs
  docs-src/antora.yml
  docs-src/modules/troubleshooting/nav.adoc
  docs-src/modules/troubleshooting/pages/logs.adoc
Labels: documentation

#270 updated buf and plugins
  .github/workflows/ci_client_cli.yml
  .github/workflows/ci_client_python.yml
  .github/workflows/ci_engine.yml
  .github/workflows/ci_proto.yml
  .github/workflows/release_engine.yml
  .github/workflows/release_python_client.yml
  .github/workflows/reusable_ci_arm64_release.yml
  .github/workflows/reusable_ci_wren.yml
  Makefile
  clients/python/src/fenlmagic/__init__.py
  clients/python/src/kaskada/formatters_helpers.py
  clients/python/src/kaskada/formatters_shared.py
  clients/python/src/kaskada/materialization.py
  clients/python/src/kaskada/query.py
  clients/python/src/kaskada/table.py
  clients/python/src/kaskada/utils.py
  clients/python/src/kaskada/view.py
  proto/buf.gen.yaml
  wren/README.md
Labels: python, wren, proto, build

#276 docs: Further refine the timelines notebook
  examples/timelines/kaskada_oss.ipynb
  examples/timelines/visualize.py
Labels: documentation

#282 bumping versions for release
  Cargo.lock
  Cargo.toml
  clients/python/pyproject.toml
  wren/.version
Labels: python, wren, sparrow

#281 Simple docs improvements
  docs-src/modules/ROOT/pages/installing.adoc
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/developing/pages/queries.adoc
  docs-src/modules/fenl/nav.adoc
  docs-src/modules/fenl/pages/catalog.adoc
  docs-src/modules/fenl/pages/fenl-quick-start.adoc
  docs-src/modules/fenl/pages/language-guide.adoc
  docs-src/modules/fenl/pages/temporal-aggregation.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Labels: documentation

#284 Use plugin for visualizations
  docs-src/modules/fenl/images/basic-aggregation.png
  docs-src/modules/fenl/images/continuous-expression.png
  docs-src/modules/fenl/images/discrete-expressions.png
  docs-src/modules/fenl/images/filtering.png
  docs-src/modules/fenl/images/final-results.png
  docs-src/modules/fenl/images/interactions-between-continuous-and-discrete.png
  docs-src/modules/fenl/images/value-stream.png
  docs-src/modules/fenl/images/windowing-example1.png
  docs-src/modules/fenl/images/windowing-example2.png
  docs-src/modules/fenl/images/windowing-example3.png
  docs-src/modules/fenl/pages/aggregation-and-windowing.adoc
  docs-src/modules/fenl/pages/continuity.adoc
  docs-src/modules/fenl/pages/temporal-aggregation.adoc
Labels: documentation

#287 Use tabs to separate different implementations of the same logic.
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/developing/pages/queries.adoc
  docs-src/modules/developing/pages/tables.adoc
Labels: documentation

#286 (docs) adds steps on releasing engine and python components
  docs/release-process.adoc
Labels: documentation

#285 Add a section to querying documenting the CLI, link to PB and Python …
  docs-src/modules/ROOT/nav.adoc
  docs-src/modules/developing/nav.adoc
  docs-src/modules/developing/pages/queries.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#290 upgraded integration tests to be runnable locally
  CONTRIBUTING.md
  Makefile
  crates/sparrow-runtime/src/s3.rs
  run.sh
  tests/integration/api/go.mod
  tests/integration/api/go.sum
  tests/integration/api/query_v1_csv_test.go
  tests/integration/api/query_v1_panic_test.go
  tests/integration/docker-compose-ci-integration.yml
  tests/integration/docker-compose.s3.yml
  tests/integration/docker-compose.yml
  tests/integration/shared/helpers/helpers.go
  wren/compute/manager.go
  wren/compute/prepare.go
  wren/service/query_v1.go
Labels: wren, sparrow
