Repository kaskada-ai/kaskada, pull requests merged in 2023-03, with the labels that each got.

#166 ref: update transaction benchmark instructions; examples
  crates/sparrow-main/benchmarks/transactions/.gitignore
  crates/sparrow-main/benchmarks/transactions/README.md
  crates/sparrow-main/benchmarks/transactions/query-column.yaml
  crates/sparrow-main/benchmarks/transactions/schema.yaml
Labels: sparrow, refactor

#172 docs: update readme
  CONTRIBUTING.md
  README.md
Labels: documentation

#173 docs: add a getting started page
  docs-src/modules/getting-started/pages/index.adoc
  docs-src/modules/overview/pages/what-is-kaskada.adoc
Labels: documentation

#170 (ci): fixes name path and git safe directory
  .github/workflows/reusable_ci_arm64_release.yml
Labels: build

#175 PyPi Release 0.1.2
  clients/python/pyproject.toml
Labels: python

#171 (ci): build and release kaskada CLI
  .github/workflows/release_engine.yml
  .github/workflows/reusable_ci_arm64_release.yml
  Dockerfile.release.dockerignore
Labels: build

#176 updated python client for new pulsar protos
  clients/python/README.md
  clients/python/src/kaskada/formatters_shared.py
  clients/python/src/kaskada/materialization.py
  clients/python/src/kaskada/table.py
  clients/python/tests/test_formatters_shared.py
  clients/python/tests/test_materialization.py
  clients/python/tests/test_table.py
Labels: python

#183 (ci): adds ubuntu-22.04 to the release matrix
  .github/workflows/release_engine.yml
Labels: build

#182 fix: fix temp file deletion
  crates/sparrow-main/src/serve/file_service.rs
  crates/sparrow-main/src/serve/preparation_service.rs
Labels: bug, sparrow

#185 fix path for cli binary
  .github/workflows/release_engine.yml
  .github/workflows/reusable_ci_arm64_release.yml
Labels: build

#184 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-report.md
Labels: build

#192 marked the pulsar auth_params field as sensitive
  proto/kaskada/kaskada/v1alpha/pulsar.proto
Labels: proto

#191 (docs): Updates paragraph around hello world links
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
  docs-src/modules/getting-started/pages/index.adoc
Labels: documentation

#193 (docs) fix broken link
  docs-src/modules/integrating/pages/integrating-with-feature-stores.adoc
Labels: documentation

#161 Demo notebook with a narrative
  examples/Kaskada Demo for Event Processing and Time-centric Calculations.ipynb
Labels: documentation

#195 Async stream pulsar
  crates/sparrow-runtime/src/execute/pulsar_reader.rs
  crates/sparrow-runtime/src/prepare.rs
Labels: sparrow

#196 (docs): update cli install instaructions
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#197 remove cert chain and redact auth from log
  crates/sparrow-main/src/prepare.rs
  crates/sparrow-runtime/src/execute/output/pulsar.rs
  crates/sparrow-runtime/src/execute/progress_reporter.rs
  proto/kaskada/kaskada/v1alpha/pulsar.proto
Labels: sparrow, proto

#123 created initial canary helm chart
  .github/workflows/ci_helm_canary.yml
  charts/kaskada-canary/.helmignore
  charts/kaskada-canary/Chart.yaml
  charts/kaskada-canary/NOTES.txt
  charts/kaskada-canary/README.md
  charts/kaskada-canary/templates/_helpers.tpl
  charts/kaskada-canary/templates/deployment.yaml
  charts/kaskada-canary/templates/persistantVolumeClaim.yaml
  charts/kaskada-canary/templates/secret.yaml
  charts/kaskada-canary/templates/service.yaml
  charts/kaskada-canary/templates/serviceAccount.yaml
  charts/kaskada-canary/tests/__snapshot__/s3_with_key_snapshot_test.yaml.snap
  charts/kaskada-canary/tests/s3_with_key_snapshot_test.yaml
  charts/kaskada-canary/tests/values/s3_with_key.yaml
  charts/kaskada-canary/values.yaml
  wren/main.go
  wren/telemetry/logging.go
Labels: wren, build

#198 (docs): fix release links
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#200 (docs): fix install command for downloading binaries on Linux and OSX
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation
