Repository kaskada-ai/kaskada, pull requests merged in 2023-10, with the labels that each got.

#786 feat: support time unit via preparing parquet from python
  crates/sparrow-catalog/src/update/execute_example.rs
  crates/sparrow-main/src/serve/compute_service.rs
  crates/sparrow-main/tests/e2e/fixture/local_table.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/prepare/execute_input_stream.rs
  crates/sparrow-runtime/src/prepare/prepare_input_stream.rs
  crates/sparrow-runtime/src/prepare/preparer.rs
  crates/sparrow-runtime/src/read/stream_reader.rs
  python/pytests/golden/parquet_source_test/test_time_column_as_float_can_cast_ns.jsonl
  python/pytests/golden/parquet_source_test/test_time_column_as_float_can_cast_s.jsonl
  python/pytests/parquet_source_test.py
  testdata/purchases/purchases_float.parquet
Labels: enhancement, sparrow, cla-signed

#782 ref: Simplify expressions in physical plan
  Cargo.lock
  Cargo.toml
  crates/sparrow-arrow/src/batch.rs
  crates/sparrow-backend/Cargo.toml
  crates/sparrow-backend/src/pipeline_schedule.rs
  crates/sparrow-execution/Cargo.toml
  crates/sparrow-execution/src/lib.rs
  crates/sparrow-expressions/src/evaluators.rs
  crates/sparrow-expressions/src/evaluators/column.rs
  crates/sparrow-expressions/src/evaluators/input.rs
  crates/sparrow-expressions/src/executor.rs
  crates/sparrow-expressions/src/lib.rs
  crates/sparrow-expressions/src/work_area.rs
  crates/sparrow-logical/Cargo.toml
  crates/sparrow-logical/src/expr.rs
  crates/sparrow-logical/src/grouping.rs
  crates/sparrow-logical/src/snapshots/sparrow_logical__expr__tests__function.snap
  crates/sparrow-physical/Cargo.toml
  crates/sparrow-physical/src/expr.rs
  crates/sparrow-physical/src/plan.rs
  crates/sparrow-physical/src/step.rs
  crates/sparrow-transforms/src/project.rs
  crates/sparrow-transforms/src/transform.rs
  crates/sparrow-transforms/src/transform_pipeline.rs
  python/Cargo.lock
Labels: sparrow, refactor, cla-signed

#784 deps: Update Arrow version
  Cargo.lock
  Cargo.toml
  crates/sparrow-arrow/src/scalar_value.rs
  crates/sparrow-catalog/catalog/div.toml
  crates/sparrow-expressions/src/evaluators/comparison/gt_primitive.rs
  crates/sparrow-expressions/src/evaluators/comparison/gte_primitive.rs
  crates/sparrow-expressions/src/evaluators/comparison/lt_primitive.rs
  crates/sparrow-expressions/src/evaluators/comparison/lte_primitive.rs
  crates/sparrow-expressions/src/evaluators/math/add.rs
  crates/sparrow-expressions/src/evaluators/math/div.rs
  crates/sparrow-expressions/src/evaluators/math/greatest.rs
  crates/sparrow-expressions/src/evaluators/math/least.rs
  crates/sparrow-expressions/src/evaluators/math/mul.rs
  crates/sparrow-expressions/src/evaluators/math/neg.rs
  crates/sparrow-expressions/src/evaluators/math/powf.rs
  crates/sparrow-expressions/src/evaluators/math/sub.rs
  crates/sparrow-instructions/Cargo.toml
  crates/sparrow-instructions/src/columnar_value.rs
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/cast.rs
  crates/sparrow-instructions/src/evaluators/comparison.rs
  crates/sparrow-instructions/src/evaluators/equality.rs
  crates/sparrow-instructions/src/evaluators/macros.rs
  crates/sparrow-instructions/src/evaluators/math.rs
  crates/sparrow-instructions/src/evaluators/math/min_max.rs
  crates/sparrow-instructions/src/evaluators/math/powf.rs
  crates/sparrow-kernels/src/time/time_delta.rs
  crates/sparrow-main/tests/e2e/list_tests.rs
  crates/sparrow-main/tests/e2e/map_tests.rs
  crates/sparrow-main/tests/e2e/notebooks/event_data_tests.rs
  crates/sparrow-main/tests/e2e/notebooks/sample_tests.rs
  crates/sparrow-main/tests/e2e/with_key_tests.rs
  crates/sparrow-merge/src/old/homogeneous_merge.rs
  crates/sparrow-runtime/Cargo.toml
  crates/sparrow-runtime/src/batch.rs
  crates/sparrow-runtime/src/execute/operation/final_tick.rs
  crates/sparrow-runtime/src/execute/operation/shift_to.rs
  crates/sparrow-runtime/src/execute/operation/shift_until.rs
  crates/sparrow-runtime/src/execute/operation/tick.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/prepare/execute_input_stream.rs
  crates/sparrow-runtime/src/prepare/prepare_input_stream.rs
  crates/sparrow-runtime/src/prepare/preparer.rs
  crates/sparrow-runtime/src/prepare/slice_preparer.rs
  crates/sparrow-runtime/src/read/stream_reader.rs
  crates/sparrow-runtime/src/read/table_reader.rs
  python/Cargo.lock
  python/Cargo.toml
  python/pytests/golden/time_test/test_compare_literal_timedelta.jsonl
Labels: sparrow, cla-signed

#791 docs: import the community page
  python/docs/source/community/index.md
  python/docs/source/index.md
Labels: documentation, cla-signed

#781 ref: move prepared files to ~/.cache dir
  Cargo.lock
  crates/sparrow-instructions/src/columnar_value.rs
  crates/sparrow-runtime/src/prepare/preparer.rs
  crates/sparrow-runtime/src/stores.rs
  crates/sparrow-runtime/src/stores/object_store_url.rs
  crates/sparrow-session/Cargo.toml
  crates/sparrow-session/src/session.rs
  crates/sparrow-session/src/table.rs
  python/Cargo.lock
  python/src/table.rs
Labels: sparrow, refactor, cla-signed

#792 feat: initial logical to physical compile
  Cargo.lock
  crates/sparrow-backend/Cargo.toml
  crates/sparrow-backend/src/compile.rs
  crates/sparrow-backend/src/error.rs
  crates/sparrow-backend/src/exprs.rs
  crates/sparrow-backend/src/exprs/expr_lang.rs
  crates/sparrow-backend/src/exprs/expr_pattern.rs
  crates/sparrow-backend/src/exprs/expr_vec.rs
  crates/sparrow-backend/src/lib.rs
  crates/sparrow-backend/src/logical_to_physical.rs
  crates/sparrow-backend/src/mutable_plan.rs
  crates/sparrow-backend/src/snapshots/sparrow_backend__logical_to_physical__tests__logical_to_physical_arithmetic-2.snap
  crates/sparrow-backend/src/snapshots/sparrow_backend__logical_to_physical__tests__logical_to_physical_arithmetic-3.snap
  crates/sparrow-backend/src/snapshots/sparrow_backend__logical_to_physical__tests__logical_to_physical_arithmetic.snap
  crates/sparrow-physical/src/step.rs
Labels: enhancement, sparrow, cla-signed

#795 bug: make file paths platform-independent
  python/pysrc/kaskada/sources/source.py
Labels: bug, cla-signed

#797 bug: uses URL instead of string to construct path to file
  Cargo.lock
  crates/sparrow-api/Cargo.toml
  crates/sparrow-api/src/kaskada/v1alpha.rs
  crates/sparrow-runtime/src/prepare/preparer.rs
  crates/sparrow-runtime/src/stores/object_store_url.rs
  python/Cargo.lock
  python/pytests/golden/parquet_source_test/test_with_space_in_path.jsonl
  python/pytests/golden/parquet_source_test/test_with_trailing_slash.jsonl
  python/pytests/parquet_source_test.py
  testdata/purchases/purchases part1.parquet
Labels: bug, sparrow, cla-signed

#796 bug: temporarily ignore parquet source tests to build windows
  python/pytests/parquet_source_test.py
Labels: bug, cla-signed

#800 Quarto tweaks
  python/README.md
  python/docs/_quarto.yml
  python/docs/_static/css/root.css
  python/docs/_static/fonts/FontAwesome6Free-Solid-900.ttf
  python/docs/_static/fonts/FontAwesome6Free-Solid-900.woff2
  python/docs/_templates/card.ejs
  python/docs/community/index.qmd
  python/docs/index.qmd
  python/noxfile.py
Labels: cla-signed

#798 feat: Support S3 paths in Parquet inputs
  .github/workflows/ci_python.yml
  crates/sparrow-runtime/src/execute/operation/spread_zip.rs
  crates/sparrow-runtime/src/lib.rs
  crates/sparrow-runtime/src/prepare/preparer.rs
  crates/sparrow-runtime/src/stores/object_store_url.rs
  crates/sparrow-session/src/lib.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-session/src/table.rs
  crates/sparrow-transforms/src/project.rs
  crates/sparrow-transforms/src/select.rs
  python/poetry.lock
  python/pyproject.toml
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/sources/arrow.py
  python/pytests/conftest.py
  python/pytests/golden/parquet_source_test/test_read_parquet_from_s3_minio.jsonl
  python/pytests/parquet_source_test.py
  python/src/lib.rs
  python/src/session.rs
  python/src/table.rs
Labels: enhancement, sparrow, build, cla-signed

#804 update param name on parquet source to match docs
  python/pysrc/kaskada/sources/arrow.py
Labels: cla-signed

#802 ref: move execution tests to a separate file
  crates/sparrow-execution/src/lib.rs
  crates/sparrow-execution/src/tests.rs
Labels: sparrow, refactor, cla-signed

#772 removed ci workflows for the engine, python client, and cli
  .github/release-drafter-engine.yml
  .github/release-drafter-python-client.yml
  .github/release-drafter-python.yml
  .github/release-drafter.yml
  .github/workflows/ci_client_cli.yml
  .github/workflows/ci_client_python.yml
  .github/workflows/ci_engine.yml
  .github/workflows/ci_notebooks.yml
  .github/workflows/ci_proto.yml
  .github/workflows/publish-antora-docs.yml
  .github/workflows/release_engine.yml
  .github/workflows/release_python_client.yml
  .github/workflows/reusable_ci_arm64_release.yml
  .github/workflows/reusable_ci_wren.yml
Labels: build, cla-signed

#808 ci: fix release drafting
  .github/release-drafter.yml
  .github/workflows/pr_labeler.yml
  .github/workflows/release_drafter.yml
Labels: cla-signed

#809 Move rust CI steps to ci_python.yml
  .github/workflows/ci_python.yml
  .github/workflows/ci_with_rust_nightly.yml
  .github/workflows/reusable_ci_rust.yml
  Cargo.lock
  crates/sparrow-api/Cargo.toml
  crates/sparrow-backend/Cargo.toml
  crates/sparrow-catalog/Cargo.toml
  crates/sparrow-compiler/Cargo.toml
  crates/sparrow-core/Cargo.toml
  crates/sparrow-instructions/Cargo.toml
  crates/sparrow-kernels/Cargo.toml
  crates/sparrow-logical/Cargo.toml
  crates/sparrow-main/Cargo.toml
  crates/sparrow-materialize/Cargo.toml
  crates/sparrow-merge/Cargo.toml
  crates/sparrow-physical/Cargo.toml
  crates/sparrow-qfr-tool/Cargo.toml
  crates/sparrow-qfr/Cargo.toml
  crates/sparrow-runtime/Cargo.toml
  crates/sparrow-scheduler/Cargo.toml
  crates/sparrow-session/Cargo.toml
  crates/sparrow-syntax/Cargo.toml
  crates/sparrow-testing/Cargo.toml
  crates/sparrow-types/Cargo.toml
  python/Cargo.lock
  python/src/session.rs
Labels: sparrow, build, cla-signed

#810 fix: release the GIL during sync iteration
  python/Cargo.lock
  python/pytests/execution_test.py
  python/src/execution.rs
Labels: bug, sparrow, cla-signed

#811 Update README.md
  README.md
Labels: cla-signed

#812 Update execution_test.py
  python/pytests/execution_test.py
Labels: cla-signed

#806 feat: compile and execute partitioned query
  Cargo.lock
  Cargo.toml
  crates/sparrow-arrow/Cargo.toml
  crates/sparrow-backend/Cargo.toml
  crates/sparrow-backend/src/compile.rs
  crates/sparrow-backend/src/logical_to_physical.rs
  crates/sparrow-backend/src/pipeline_schedule.rs
  crates/sparrow-backend/src/snapshots/sparrow_backend__logical_to_physical__tests__logical_to_physical_arithmetic-2.snap
  crates/sparrow-backend/src/snapshots/sparrow_backend__logical_to_physical__tests__logical_to_physical_arithmetic-3.snap
  crates/sparrow-backend/src/snapshots/sparrow_backend__logical_to_physical__tests__logical_to_physical_arithmetic.snap
  crates/sparrow-batch/src/batch.rs
  crates/sparrow-compiler/Cargo.toml
  crates/sparrow-execution/Cargo.toml
  crates/sparrow-execution/src/error.rs
  crates/sparrow-execution/src/lib.rs
  crates/sparrow-execution/src/source_tasks.rs
  crates/sparrow-execution/src/tests.rs
  crates/sparrow-execution/src/write_channel_pipeline.rs
  crates/sparrow-expressions/src/error.rs
  crates/sparrow-expressions/src/evaluators.rs
  crates/sparrow-expressions/src/evaluators/fieldref.rs
  crates/sparrow-expressions/src/lib.rs
  crates/sparrow-interfaces/Cargo.toml
  crates/sparrow-interfaces/src/execution_options.rs
  crates/sparrow-interfaces/src/lib.rs
  crates/sparrow-interfaces/src/source.rs
  crates/sparrow-logical/src/error.rs
  crates/sparrow-logical/src/expr.rs
  crates/sparrow-logical/src/typecheck.rs
  crates/sparrow-merge/Cargo.toml
  crates/sparrow-physical/Cargo.toml
  crates/sparrow-physical/src/plan.rs
  crates/sparrow-physical/src/step.rs
  crates/sparrow-scheduler/Cargo.toml
  crates/sparrow-scheduler/src/error.rs
  crates/sparrow-scheduler/src/idle_workers.rs
  crates/sparrow-scheduler/src/input_handles.rs
  crates/sparrow-scheduler/src/lib.rs
  crates/sparrow-scheduler/src/monitor.rs
  crates/sparrow-scheduler/src/queue.rs
  crates/sparrow-scheduler/src/schedule_count.rs
  crates/sparrow-scheduler/src/sink.rs
  crates/sparrow-scheduler/src/task.rs
  crates/sparrow-scheduler/src/worker.rs
  crates/sparrow-scheduler/src/worker_pool.rs
  crates/sparrow-session/Cargo.toml
  crates/sparrow-session/src/execution.rs
  crates/sparrow-session/src/lib.rs
  crates/sparrow-session/src/partitioned.rs
  crates/sparrow-session/src/partitioned/session.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-sources/Cargo.toml
  crates/sparrow-sources/src/in_memory.rs
  crates/sparrow-transforms/src/lib.rs
  crates/sparrow-transforms/src/project.rs
  crates/sparrow-transforms/src/select.rs
  crates/sparrow-transforms/src/transform_pipeline.rs
  python/Cargo.lock
  python/Cargo.toml
  python/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#815 Update release_python.yml
  .github/workflows/release_python.yml
Labels: build, cla-signed

#816 ref: Move source to a public module in interfaces
  crates/sparrow-execution/src/lib.rs
  crates/sparrow-execution/src/source_tasks.rs
  crates/sparrow-execution/src/tests.rs
  crates/sparrow-interfaces/src/lib.rs
  crates/sparrow-interfaces/src/source.rs
  crates/sparrow-interfaces/src/source_error.rs
  crates/sparrow-session/src/partitioned/session.rs
  crates/sparrow-sources/src/in_memory.rs
Labels: sparrow, refactor, cla-signed

#817 ref: Rename sparrow-execution to sparrow-plan-execution
  Cargo.lock
  crates/sparrow-plan-execution/Cargo.toml
  crates/sparrow-plan-execution/src/error.rs
  crates/sparrow-plan-execution/src/lib.rs
  crates/sparrow-plan-execution/src/source_tasks.rs
  crates/sparrow-plan-execution/src/tests.rs
  crates/sparrow-plan-execution/src/write_channel_pipeline.rs
  crates/sparrow-session/Cargo.toml
  crates/sparrow-session/src/partitioned/session.rs
  python/Cargo.lock
Labels: sparrow, refactor, cla-signed

#822 fix: Permissions on the release job
  .github/workflows/release_python.yml
Labels: bug, build, cla-signed

#821 test: add in-memory batch unit tests
  Cargo.lock
  crates/sparrow-sources/Cargo.toml
  crates/sparrow-sources/src/in_memory.rs
Labels: sparrow, test, cla-signed

#824 ref: rename sparrow-sources to sparrow-io
  Cargo.lock
  Cargo.toml
  crates/sparrow-compiler/Cargo.toml
  crates/sparrow-compiler/src/data_context.rs
  crates/sparrow-io/Cargo.toml
  crates/sparrow-io/src/in_memory.rs
  crates/sparrow-io/src/in_memory/source.rs
  crates/sparrow-io/src/lib.rs
  crates/sparrow-plan-execution/Cargo.toml
  crates/sparrow-plan-execution/src/tests.rs
  crates/sparrow-session/Cargo.toml
  crates/sparrow-session/src/table.rs
Labels: sparrow, refactor, cla-signed

#826 updated reddit example for quarto
  python/docs/examples/reddit.qmd
Labels: cla-signed

#827 feat: add gatherer for sparrow-merge
  Cargo.lock
  crates/sparrow-batch/Cargo.toml
  crates/sparrow-batch/src/batch.rs
  crates/sparrow-merge/Cargo.toml
  crates/sparrow-merge/src/gather.rs
  crates/sparrow-merge/src/lib.rs
Labels: enhancement, sparrow, cla-signed

#829 docs: remove alpha banner
  python/Cargo.lock
  python/docs/_quarto.yml
  python/docs/_static/css/styles.css
  python/docs/_templates/announcement.html
Labels: documentation, sparrow, cla-signed

#830 Update README.md
  README.md
Labels: cla-signed

#831 Update installation.qmd
  python/docs/guide/installation.qmd
Labels: cla-signed

#835 added READMEs and simplified CI
  .github/workflows/ci_python.yml
  python/docs/_extensions/README.md
  python/docs/_scripts/README.md
Labels: build, cla-signed

#833 updated docs for 2 examples
  python/docs/examples/_metadata.yml
  python/docs/examples/bluesky.py
  python/docs/examples/bluesky.qmd
  python/docs/examples/time_centric.ipynb
  python/docs/examples/time_centric.qmd
Labels: cla-signed

#837 fix: noxfile copy pasta
  python/noxfile.py
Labels: bug, cla-signed

#828 feat: partitioned merge pipeline
  Cargo.lock
  crates/sparrow-batch/src/batch.rs
  crates/sparrow-io/src/channel.rs
  crates/sparrow-merge/Cargo.toml
  crates/sparrow-merge/src/gather.rs
  crates/sparrow-merge/src/lib.rs
  crates/sparrow-merge/src/merge.rs
  crates/sparrow-merge/src/merge/binary_merge.rs
  crates/sparrow-merge/src/merge/heterogeneous_merge.rs
  crates/sparrow-merge/src/merge_pipeline.rs
  crates/sparrow-merge/src/spread.rs
  crates/sparrow-plan-execution/Cargo.toml
  crates/sparrow-plan-execution/src/lib.rs
  crates/sparrow-transforms/src/transform_pipeline.rs
Labels: enhancement, sparrow, cla-signed

#838 feat: add destination/writer trait
  Cargo.lock
  Cargo.toml
  crates/sparrow-interfaces/Cargo.toml
  crates/sparrow-interfaces/src/destination.rs
  crates/sparrow-interfaces/src/lib.rs
  crates/sparrow-interfaces/src/types.rs
  crates/sparrow-interfaces/src/types/partition.rs
  crates/sparrow-io/Cargo.toml
  crates/sparrow-io/src/channel.rs
  crates/sparrow-io/src/channel/destination.rs
  crates/sparrow-io/src/lib.rs
  crates/sparrow-merge/Cargo.toml
  crates/sparrow-merge/src/merge_pipeline.rs
  crates/sparrow-plan-execution/src/lib.rs
  crates/sparrow-plan-execution/src/write_channel_pipeline.rs
  crates/sparrow-plan-execution/src/write_pipeline.rs
  crates/sparrow-scheduler/Cargo.toml
  crates/sparrow-scheduler/src/error.rs
  crates/sparrow-scheduler/src/input_handles.rs
  crates/sparrow-scheduler/src/lib.rs
  crates/sparrow-scheduler/src/pipeline.rs
  crates/sparrow-scheduler/src/schedule_count.rs
  crates/sparrow-scheduler/src/task.rs
  crates/sparrow-scheduler/src/worker_pool.rs
  crates/sparrow-transforms/Cargo.toml
  crates/sparrow-transforms/src/transform_pipeline.rs
Labels: enhancement, sparrow, cla-signed
