Repository kaskada-ai/kaskada, pull requests merged in 2023-08, with the labels that each got.

#577 bug: fix default schema in inference for map/list
  crates/sparrow-compiler/src/types/inference.rs
  crates/sparrow-main/tests/e2e/list_tests.rs
  crates/sparrow-main/tests/e2e/map_tests.rs
Labels: bug, sparrow, cla-signed

#542 removed redis destination
  CONTRIBUTING.md
  Makefile
  clients/python/src/kaskada/formatters.py
  clients/python/src/kaskada/formatters_shared.py
  clients/python/src/kaskada/materialization.py
  clients/python/tests/test_materialization.py
  crates/sparrow-runtime/src/execute/output.rs
  crates/sparrow-runtime/src/execute/output/redis.rs
  crates/sparrow-runtime/src/execute/progress_reporter.rs
  docs-src/modules/developing/pages/queries.adoc
  docs-src/modules/installing/pages/local.adoc
  examples/Customer_Retention_(OSS).ipynb
  proto/kaskada/kaskada/v1alpha/destinations.proto
  proto/kaskada/kaskada/v1alpha/query_service.proto
  proto/kaskada/kaskada/v2alpha/query_service.proto
  tests/integration/api/api_suite_test.go
  tests/integration/api/go.mod
  tests/integration/api/go.sum
  tests/integration/api/graceful_shutdown_test.go
  tests/integration/api/materializations_test.go
  tests/integration/api/queries_v2_test.go
  tests/integration/api/query_v1_rest_test.go
  tests/integration/api/query_v1_test.go
  tests/integration/api/tables_test.go
  tests/integration/cli/cli_suite_test.go
  tests/integration/docker-compose.yml
  tests/integration/shared/go.mod
  tests/integration/shared/go.sum
  tests/integration/shared/helpers/helpers.go
  wren/client/object_store_client.go
  wren/compute/compute_manager.go
  wren/go.sum
  wren/property/query_result_type.go
  wren/service/query_v1.go
Labels: documentation, python, wren, sparrow, proto, cla-signed

#575 feat: Execute Python queries
  Cargo.lock
  crates/sparrow-compiler/src/data_context.rs
  crates/sparrow-compiler/src/dfg.rs
  crates/sparrow-compiler/src/lib.rs
  crates/sparrow-compiler/src/plan.rs
  crates/sparrow-main/tests/e2e/fixture/query_fixture.rs
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/compute_executor.rs
  crates/sparrow-runtime/src/execute/compute_store_guard.rs
  crates/sparrow-runtime/src/execute/key_hash_inverse.rs
  crates/sparrow-runtime/src/execute/operation.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/execute/operation/testing.rs
  crates/sparrow-runtime/src/execute/progress_reporter.rs
  crates/sparrow-session/Cargo.toml
  crates/sparrow-session/src/error.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-session/src/table.rs
  sparrow-py/Cargo.lock
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/expr.py
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/table_test.py
  sparrow-py/src/expr.rs
  sparrow-py/src/table.rs
Labels: enhancement, sparrow, cla-signed

#579 ref: Switch to a global session
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/session.py
  sparrow-py/pysrc/sparrow_py/table.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/expr_test.py
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/table_test.py
Labels: refactor, cla-signed

#581 ref: Cleanup sources in Python
  sparrow-py/.darglint
  sparrow-py/.flake8
  sparrow-py/noxfile.py
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/expr.py
  sparrow-py/pysrc/sparrow_py/session.py
  sparrow-py/pysrc/sparrow_py/sources/__init__.py
  sparrow-py/pysrc/sparrow_py/sources/arrow.py
  sparrow-py/pysrc/sparrow_py/sources/source.py
  sparrow-py/pysrc/sparrow_py/udf.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/expr_test.py
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/source_test.py
  sparrow-py/pytests/udf_test.py
Labels: refactor, cla-signed

#573 feat: OpenAI Example Notebook
  examples/slackbot/Notebook.ipynb
  examples/slackbot/OpenAI.ipynb
Labels: enhancement, cla-signed

#582 feat: Add record field manipulation
  crates/sparrow-session/src/expr.rs
  crates/sparrow-session/src/session.rs
  sparrow-py/poetry.lock
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/expr.py
  sparrow-py/pysrc/sparrow_py/math.py
  sparrow-py/pytests/expr_test.py
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/source_test.py
  sparrow-py/pytests/udf_test.py
Labels: enhancement, sparrow, cla-signed

#583 feat: support since windows in collect aggregations
  crates/sparrow-compiler/src/ast_to_dfg/window_args.rs
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__count_since_window.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__since_daily.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__since_daily_multiple_passes.snap
  crates/sparrow-instructions/src/evaluators/aggregation/token/collect_token.rs
  crates/sparrow-instructions/src/evaluators/list/collect_boolean.rs
  crates/sparrow-instructions/src/evaluators/list/collect_primitive.rs
  crates/sparrow-instructions/src/evaluators/list/collect_string.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
  crates/sparrow-runtime/src/execute/operation/tick.rs
Labels: enhancement, sparrow, cla-signed

#585 release: update python and sparrow version
  Cargo.lock
  Cargo.toml
  clients/python/pyproject.toml
  wren/.version
Labels: python, wren, sparrow, release, cla-signed

#587 bug: correctly type-check user facing aggregation signatures
  crates/sparrow-compiler/src/frontend/resolve_arguments.rs
  crates/sparrow-compiler/src/functions/aggregation.rs
  crates/sparrow-compiler/src/functions/function.rs
  crates/sparrow-plan/src/inst.rs
Labels: bug, sparrow, cla-signed

#586 feat: Support aggregation functions in Python
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/dfg.rs
  crates/sparrow-compiler/src/dfg/useless_transforms.rs
  crates/sparrow-compiler/src/diagnostics/collector.rs
  crates/sparrow-compiler/src/lib.rs
  crates/sparrow-session/src/expr.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-syntax/src/syntax/signature.rs
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_windows.py
  sparrow-py/pysrc/sparrow_py/expr.py
  sparrow-py/pysrc/sparrow_py/udf.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/udf_test.py
  sparrow-py/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#590 fix: Aggregations in sparrow-py
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/functions/function.rs
  crates/sparrow-session/src/session.rs
  sparrow-py/Cargo.lock
  sparrow-py/pytests/expr_test.py
Labels: bug, sparrow, cla-signed

#589 test: Introduce a golden test helper for Python
  sparrow-py/pyproject.toml
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/_windows.py
  sparrow-py/pysrc/sparrow_py/expr.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/golden/aggregation_test/test_sum_unwindowed.csv
  sparrow-py/pytests/golden/aggregation_test/test_sum_windowed.csv
  sparrow-py/pytests/golden/math_test/test_math_int64.csv
  sparrow-py/pytests/golden/record_test/test_extend_record.csv
  sparrow-py/pytests/golden/record_test/test_record.csv
  sparrow-py/pytests/golden/record_test/test_select_record.csv
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/record_test.py
Labels: test, cla-signed

#593 feat: Allow adding more data to a table
  crates/sparrow-runtime/src/merge.rs
  crates/sparrow-runtime/src/merge/homogeneous_merge.rs
  crates/sparrow-session/src/table.rs
  sparrow-py/pysrc/sparrow_py/sources/arrow.py
  sparrow-py/pytests/golden/source_test/test_add_dataframe.csv
  sparrow-py/pytests/golden/source_test/test_add_dataframe_1.csv
  sparrow-py/pytests/source_test.py
Labels: enhancement, sparrow, cla-signed

#592 feat: add first/last list non-windowed aggregation support
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/aggregation.rs
  crates/sparrow-instructions/src/evaluators/aggregation/list.rs
  crates/sparrow-instructions/src/evaluators/aggregation/list/first_list_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/list/last_list_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/list_accum_token.rs
  crates/sparrow-instructions/src/evaluators/equality.rs
  crates/sparrow-instructions/src/evaluators/list.rs
  crates/sparrow-instructions/src/evaluators/list/collect_list.rs
  crates/sparrow-instructions/src/evaluators/macros.rs
  crates/sparrow-main/tests/e2e/list_tests.rs
Labels: enhancement, sparrow, cla-signed

#594 add support for json and make that the default
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/golden/aggregation_test/test_sum_unwindowed.csv
  sparrow-py/pytests/golden/aggregation_test/test_sum_unwindowed.json
  sparrow-py/pytests/golden/aggregation_test/test_sum_windowed.csv
  sparrow-py/pytests/golden/aggregation_test/test_sum_windowed.json
  sparrow-py/pytests/golden/collect_test/test_collect_basic.csv
  sparrow-py/pytests/golden/collect_test/test_collect_basic.json
  sparrow-py/pytests/golden/collect_test/test_collect_with_max.csv
  sparrow-py/pytests/golden/collect_test/test_collect_with_max.json
  sparrow-py/pytests/golden/math_test/test_math_int64.csv
  sparrow-py/pytests/golden/math_test/test_math_int64.json
  sparrow-py/pytests/golden/record_test/test_extend_record.csv
  sparrow-py/pytests/golden/record_test/test_extend_record.json
  sparrow-py/pytests/golden/record_test/test_record.csv
  sparrow-py/pytests/golden/record_test/test_record.json
  sparrow-py/pytests/golden/record_test/test_select_record.csv
  sparrow-py/pytests/golden/record_test/test_select_record.json
Labels: cla-signed

#597 added timestreams placeholder project
  clients/docker-compose.yml
  clients/timestreams/README.md
  clients/timestreams/poetry.lock
  clients/timestreams/pyproject.toml
  clients/timestreams/src/timestreams/__init__.py
Labels: cla-signed

#596 feat: Expose execution control from Rust to Python
  crates/sparrow-session/src/error.rs
  crates/sparrow-session/src/execution.rs
  crates/sparrow-session/src/lib.rs
  crates/sparrow-session/src/session.rs
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/expr.py
  sparrow-py/src/error.rs
  sparrow-py/src/execution.rs
  sparrow-py/src/expr.rs
  sparrow-py/src/lib.rs
Labels: enhancement, sparrow, cla-signed

#595 feat: sparrow py collect function
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/dfg.rs
  crates/sparrow-compiler/src/functions/collection.rs
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/expr.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/golden/aggregation_test/test_sum_unwindowed.csv
  sparrow-py/pytests/golden/aggregation_test/test_sum_unwindowed.json
  sparrow-py/pytests/golden/aggregation_test/test_sum_windowed.csv
  sparrow-py/pytests/golden/aggregation_test/test_sum_windowed.json
  sparrow-py/pytests/golden/collect_test/test_collect_basic.json
  sparrow-py/pytests/golden/collect_test/test_collect_since_window.json
  sparrow-py/pytests/golden/collect_test/test_collect_with_max.json
  sparrow-py/pytests/golden/math_test/test_math_int64.csv
  sparrow-py/pytests/golden/math_test/test_math_int64.json
  sparrow-py/pytests/golden/record_test/test_extend_record.csv
  sparrow-py/pytests/golden/record_test/test_extend_record.json
  sparrow-py/pytests/golden/record_test/test_record.csv
  sparrow-py/pytests/golden/record_test/test_record.json
  sparrow-py/pytests/golden/record_test/test_select_record.csv
  sparrow-py/pytests/golden/record_test/test_select_record.json
Labels: enhancement, sparrow, cla-signed

#598 feat: More work on Python API
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-session/src/lib.rs
  crates/sparrow-session/src/session.rs
  sparrow-py/.darglint
  sparrow-py/noxfile.py
  sparrow-py/pyproject.toml
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_expr.py
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/_result.py
  sparrow-py/pysrc/sparrow_py/_session.py
  sparrow-py/pysrc/sparrow_py/_windows.py
  sparrow-py/pysrc/sparrow_py/sources/source.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/expr_test.py
  sparrow-py/pytests/golden/aggregation_test/test_sum_unwindowed.json
  sparrow-py/pytests/golden/aggregation_test/test_sum_windowed.json
  sparrow-py/pytests/golden/collect_test/test_collect_basic.json
  sparrow-py/pytests/golden/collect_test/test_collect_since_window.json
  sparrow-py/pytests/golden/collect_test/test_collect_with_max.json
  sparrow-py/pytests/golden/math_test/test_math_int64.json
  sparrow-py/pytests/golden/record_test/test_extend_record.json
  sparrow-py/pytests/golden/record_test/test_record.json
  sparrow-py/pytests/golden/record_test/test_select_record.json
  sparrow-py/pytests/golden/source_test/test_add_dataframe.csv
  sparrow-py/pytests/golden/source_test/test_add_dataframe.json
  sparrow-py/pytests/golden/source_test/test_add_dataframe_1.csv
  sparrow-py/pytests/golden/source_test/test_add_dataframe_1.json
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/source_test.py
  sparrow-py/src/execution.rs
  sparrow-py/src/expr.rs
  sparrow-py/src/lib.rs
Labels: enhancement, sparrow, cla-signed

#599 lint: Fix misc lint problems
  sparrow-py/.flake8
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_expr.py
  sparrow-py/pysrc/sparrow_py/sources/source.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/conftest.py
Labels: cla-signed

#600 ref: Use a dataclass for execution options
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_execution.py
  sparrow-py/pysrc/sparrow_py/_expr.py
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/_windows.py
  sparrow-py/src/execution.rs
  sparrow-py/src/expr.rs
  sparrow-py/src/lib.rs
Labels: refactor, cla-signed

#601 feat: Introduce the Result class
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/compute_executor.rs
  crates/sparrow-runtime/src/execute/output.rs
  crates/sparrow-runtime/src/lib.rs
  crates/sparrow-session/src/session.rs
  sparrow-py/noxfile.py
  sparrow-py/pysrc/sparrow_py/_execution.py
  sparrow-py/pysrc/sparrow_py/_expr.py
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/_result.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/expr_test.py
  sparrow-py/pytests/golden/expr_test/test_expr_preview.json
  sparrow-py/pytests/golden/result_test/test_iterate_pandas.json
  sparrow-py/pytests/golden/result_test/test_iterate_pandas_1.json
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/result_test.py
  sparrow-py/pytests/source_test.py
  sparrow-py/pytests/udf_test.py
  sparrow-py/src/execution.rs
  sparrow-py/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#603 feat: Rename `Expr` to `Timestream`; stub docs
  crates/sparrow-session/src/expr.rs
  sparrow-py/.flake8
  sparrow-py/README.md
  sparrow-py/docs/conf.py
  sparrow-py/docs/index.md
  sparrow-py/docs/quickstart.md
  sparrow-py/docs/reference/execution.md
  sparrow-py/docs/reference/sources.md
  sparrow-py/docs/reference/timestream.md
  sparrow-py/noxfile.py
  sparrow-py/poetry.lock
  sparrow-py/pyproject.toml
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_execution.py
  sparrow-py/pysrc/sparrow_py/_expr.py
  sparrow-py/pysrc/sparrow_py/_result.py
  sparrow-py/pysrc/sparrow_py/_session.py
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pysrc/sparrow_py/_windows.py
  sparrow-py/pysrc/sparrow_py/sources/source.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/golden/record_test/test_remove_record.json
  sparrow-py/pytests/golden/record_test/test_select_record.json
  sparrow-py/pytests/golden/timestream_test/test_timestream_preview.json
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/result_test.py
  sparrow-py/pytests/timestream_test.py
  sparrow-py/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#602 feat: support `DataType::Struct` in collect function
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/collect_struct_token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/map_accum_token.rs
  crates/sparrow-instructions/src/evaluators/equality.rs
  crates/sparrow-instructions/src/evaluators/list.rs
  crates/sparrow-instructions/src/evaluators/list/collect_struct.rs
  crates/sparrow-instructions/src/evaluators/macros.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
Labels: enhancement, sparrow, cla-signed

#604 feat: Allow running non-record columns
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pysrc/sparrow_py/sources/arrow.py
  sparrow-py/pytests/golden/timestream_test/test_timestream_run_non_record.json
  sparrow-py/pytests/timestream_test.py
Labels: enhancement, cla-signed

#609 feat: add list_len function
  crates/sparrow-compiler/src/functions/collection.rs
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/list.rs
  crates/sparrow-instructions/src/evaluators/list/list_len.rs
  crates/sparrow-main/tests/e2e/list_tests.rs
  crates/sparrow-plan/src/inst.rs
Labels: enhancement, sparrow, cla-signed

#610 docs: Some doc tweaks
  sparrow-py/README.md
  sparrow-py/docs/source/conf.py
  sparrow-py/docs/source/index.md
  sparrow-py/docs/source/reference/timestream/index.md
  sparrow-py/poetry.lock
  sparrow-py/pyproject.toml
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_timestream.py
Labels: documentation, cla-signed

#608 ref: Introduce a class for golden tests
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/golden/aggregation_test/test_sum_unwindowed.jsonl
  sparrow-py/pytests/golden/aggregation_test/test_sum_windowed.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_basic.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_since_window.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_with_max.jsonl
  sparrow-py/pytests/golden/math_test/test_math_int64.jsonl
  sparrow-py/pytests/golden/record_test/test_extend_record.jsonl
  sparrow-py/pytests/golden/record_test/test_record.jsonl
  sparrow-py/pytests/golden/record_test/test_remove_record.jsonl
  sparrow-py/pytests/golden/record_test/test_select_record.jsonl
  sparrow-py/pytests/golden/result_test/test_iterate_pandas.jsonl
  sparrow-py/pytests/golden/result_test/test_iterate_pandas_1.jsonl
  sparrow-py/pytests/golden/source_test/test_add_dataframe.jsonl
  sparrow-py/pytests/golden/source_test/test_add_dataframe_1.jsonl
  sparrow-py/pytests/golden/timestream_test/test_timestream_preview.json
  sparrow-py/pytests/golden/timestream_test/test_timestream_preview.jsonl
  sparrow-py/pytests/golden/timestream_test/test_timestream_run_non_record.jsonl
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/result_test.py
  sparrow-py/pytests/source_test.py
  sparrow-py/pytests/timestream_test.py
Labels: refactor, cla-signed

#607 feat: add min parameter to collect
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/functions/collection.rs
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/list/collect_boolean.rs
  crates/sparrow-instructions/src/evaluators/list/collect_primitive.rs
  crates/sparrow-instructions/src/evaluators/list/collect_string.rs
  crates/sparrow-instructions/src/evaluators/list/collect_struct.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
  crates/sparrow-plan/src/inst.rs
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/golden/collect_test/test_collect_with_min.json
  sparrow-py/pytests/golden/collect_test/test_collect_with_min_and_max.json
Labels: enhancement, sparrow, cla-signed

#606 feat: Async iteration through Rust
  crates/sparrow-session/src/execution.rs
  sparrow-py/Cargo.lock
  sparrow-py/Cargo.toml
  sparrow-py/README.md
  sparrow-py/docs/source/conf.py
  sparrow-py/noxfile.py
  sparrow-py/poetry.lock
  sparrow-py/pyproject.toml
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/_result.py
  sparrow-py/pytests/golden/result_test/test_iter_pandas.jsonl
  sparrow-py/pytests/golden/result_test/test_iter_pandas_1.jsonl
  sparrow-py/pytests/golden/result_test/test_iter_pandas_async.jsonl
  sparrow-py/pytests/golden/result_test/test_iter_pandas_async_1.jsonl
  sparrow-py/pytests/result_test.py
  sparrow-py/src/error.rs
  sparrow-py/src/execution.rs
Labels: enhancement, sparrow, cla-signed

#612 feat: more basic function in sparrow py
  crates/sparrow-compiler/src/ast_to_dfg.rs
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/filter_test.py
  sparrow-py/pytests/golden/filter_test/test_filter.json
  sparrow-py/pytests/golden/if_test/test_if_.json
  sparrow-py/pytests/golden/lag_test/test_lag.json
  sparrow-py/pytests/golden/length_test/test_length.json
  sparrow-py/pytests/golden/lookup_test/test_lookup.json
  sparrow-py/pytests/golden/null_if_test/test_null_if.json
  sparrow-py/pytests/golden/time_of_test/test_time_of.json
  sparrow-py/pytests/golden/with_key_test/test_with_key_column.json
  sparrow-py/pytests/golden/with_key_test/test_with_key_grouping.json
  sparrow-py/pytests/golden/with_key_test/test_with_key_literal.json
  sparrow-py/pytests/if_test.py
  sparrow-py/pytests/lag_test.py
  sparrow-py/pytests/length_test.py
  sparrow-py/pytests/lookup_test.py
  sparrow-py/pytests/null_if_test.py
  sparrow-py/pytests/time_of_test.py
  sparrow-py/pytests/with_key_test.py
Labels: enhancement, sparrow, cla-signed

#613 fix: docs-build in noxfile
  sparrow-py/noxfile.py
Labels: bug, cla-signed

#615 feat: Add basic time arithmetic
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/filter_test.py
  sparrow-py/pytests/golden/collect_test/test_collect_with_min.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_with_min_and_max.jsonl
  sparrow-py/pytests/golden/filter_test/test_filter.jsonl
  sparrow-py/pytests/golden/if_test/test_if_.jsonl
  sparrow-py/pytests/golden/lag_test/test_lag.jsonl
  sparrow-py/pytests/golden/length_test/test_length.jsonl
  sparrow-py/pytests/golden/lookup_test/test_lookup.jsonl
  sparrow-py/pytests/golden/null_if_test/test_null_if.jsonl
  sparrow-py/pytests/golden/time_of_test/test_time_of.jsonl
  sparrow-py/pytests/golden/time_test/test_time_add_days.jsonl
  sparrow-py/pytests/golden/time_test/test_time_add_days_and_minutes.jsonl
  sparrow-py/pytests/golden/time_test/test_time_add_hours.jsonl
  sparrow-py/pytests/golden/time_test/test_time_add_minutes.jsonl
  sparrow-py/pytests/golden/time_test/test_time_add_seconds.jsonl
  sparrow-py/pytests/golden/with_key_test/test_with_key_column.jsonl
  sparrow-py/pytests/golden/with_key_test/test_with_key_grouping.jsonl
  sparrow-py/pytests/golden/with_key_test/test_with_key_literal.jsonl
  sparrow-py/pytests/if_test.py
  sparrow-py/pytests/lag_test.py
  sparrow-py/pytests/length_test.py
  sparrow-py/pytests/lookup_test.py
  sparrow-py/pytests/null_if_test.py
  sparrow-py/pytests/time_of_test.py
  sparrow-py/pytests/time_test.py
  sparrow-py/pytests/with_key_test.py
Labels: enhancement, cla-signed

#616 feat: ignore null values in collect
  crates/sparrow-instructions/src/evaluators/list/collect_boolean.rs
  crates/sparrow-instructions/src/evaluators/list/collect_primitive.rs
  crates/sparrow-instructions/src/evaluators/list/collect_string.rs
  crates/sparrow-instructions/src/evaluators/list/collect_struct.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
  crates/sparrow-main/tests/e2e/list_tests.rs
  sparrow-py/pytests/golden/collect_test/test_collect_basic.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_with_max.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_with_min.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_with_min_and_max.jsonl
  sparrow-py/pytests/golden/length_test/test_length.jsonl
Labels: enhancement, sparrow, cla-signed

#550 docs update code sample around creating/using session
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/developing/pages/materializations.adoc
  docs-src/modules/developing/pages/tables.adoc
  docs-src/modules/developing/pages/views.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Labels: documentation, cla-signed

#622 make some updates
  examples/slackbot/Notebook.ipynb
Labels: cla-signed

#614 Update notebook per Eric's prep steps
  examples/slackbot/Notebook.ipynb
Labels: cla-signed

#618 docs: some polishing / landing page work
  sparrow-py/docs/source/_extensions/gallery_directive.py
  sparrow-py/docs/source/conf.py
  sparrow-py/docs/source/guide/introduction.md
  sparrow-py/docs/source/index.md
  sparrow-py/noxfile.py
  sparrow-py/poetry.lock
  sparrow-py/pyproject.toml
Labels: documentation, cla-signed

#623 feat: Support casting timestreams
  crates/sparrow-session/src/session.rs
  sparrow-py/pysrc/sparrow_py/_ffi.pyi
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/golden/timestream_test/test_timestream_cast.jsonl
  sparrow-py/pytests/timestream_test.py
  sparrow-py/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#624 feat: Introduce `col` method for field access
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/filter_test.py
  sparrow-py/pytests/if_test.py
  sparrow-py/pytests/lag_test.py
  sparrow-py/pytests/length_test.py
  sparrow-py/pytests/lookup_test.py
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/null_if_test.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/time_of_test.py
  sparrow-py/pytests/time_test.py
  sparrow-py/pytests/timestream_test.py
  sparrow-py/pytests/with_key_test.py
Labels: enhancement, cla-signed

#625 feat: implement lag with collect
  crates/sparrow-compiler/src/dfg/const_eval.rs
  crates/sparrow-compiler/src/frontend/incremental_enabled.rs
  crates/sparrow-compiler/src/functions/time.rs
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/lag_token.rs
  crates/sparrow-instructions/src/evaluators/time.rs
  crates/sparrow-kernels/src/lag.rs
  crates/sparrow-kernels/src/lib.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
  crates/sparrow-main/tests/e2e/resumeable_tests.rs
  crates/sparrow-main/tests/e2e/time_tests.rs
  crates/sparrow-plan/src/inst.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
Labels: enhancement, sparrow, cla-signed

#626 Break the bot out into a script, fix a couple bits
  examples/slackbot/Notebook.ipynb
  examples/slackbot/slackbot.py
Labels: cla-signed

#628 feat: Support arithmetic chains
  sparrow-py/pysrc/sparrow_py/_execution.py
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pysrc/sparrow_py/sources/arrow.py
  sparrow-py/pytests/golden/lag_test/test_lag.jsonl
  sparrow-py/pytests/source_test.py
Labels: enhancement, cla-signed

#627 feat: Add a flatten operation
  crates/sparrow-compiler/src/functions/collection.rs
  crates/sparrow-compiler/src/types/inference.rs
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/list.rs
  crates/sparrow-instructions/src/evaluators/list/flatten.rs
  crates/sparrow-plan/src/inst.rs
  crates/sparrow-syntax/src/parser.rs
  crates/sparrow-syntax/src/parser/grammar.lalrpop
  crates/sparrow-syntax/src/syntax/fenl_type.rs
  crates/sparrow-syntax/src/syntax/signature.rs
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/flatten_test.py
Labels: enhancement, sparrow, cla-signed

#630 feat: Support field-ref on lists of structs
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/types/instruction.rs
  crates/sparrow-instructions/src/evaluators/field_ref.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/golden/collect_test/test_collect_records.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_records_field_ref.jsonl
Labels: enhancement, sparrow, cla-signed

#633 feat: hack collect lists by wrapping in struct
  crates/sparrow-main/tests/e2e/collect_tests.rs
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/flatten_test.py
  sparrow-py/pytests/golden/collect_test/test_collect_lists.jsonl
Labels: enhancement, sparrow, cla-signed

#634 feat: Support boolean literals
  crates/sparrow-session/src/expr.rs
  crates/sparrow-session/src/session.rs
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/golden/aggregation_test/test_sum_since_true.jsonl
  sparrow-py/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#631 updated slackbot script
  examples/slackbot/Notebook.ipynb
  examples/slackbot/slackbot.py
  examples/slackbot/user_output_map.json
Labels: cla-signed

#636 feat: Add the trailing window
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pysrc/sparrow_py/windows.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/collect_test.py
Labels: enhancement, cla-signed

#637 feat: Unlatched spread for all the things
  crates/sparrow-runtime/src/execute/operation/spread.rs
Labels: enhancement, sparrow, cla-signed

#638 feat: add since window for structs
  crates/sparrow-compiler/src/functions/collection.rs
  crates/sparrow-instructions/src/evaluators/list/collect_boolean.rs
  crates/sparrow-instructions/src/evaluators/list/collect_primitive.rs
  crates/sparrow-instructions/src/evaluators/list/collect_string.rs
  crates/sparrow-instructions/src/evaluators/list/collect_struct.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
Labels: enhancement, sparrow, cla-signed

#639 feat: Update key hash inverses as new data arrives
  Cargo.lock
  crates/sparrow-runtime/Cargo.toml
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/operation.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/execute/operation/testing.rs
  crates/sparrow-runtime/src/execute/operation/with_key.rs
  crates/sparrow-runtime/src/execute/output.rs
  crates/sparrow-runtime/src/key_hash_inverse.rs
  crates/sparrow-runtime/src/lib.rs
  crates/sparrow-runtime/src/prepare/execute_input_stream.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-session/src/table.rs
  sparrow-py/Cargo.lock
  sparrow-py/noxfile.py
  sparrow-py/pysrc/sparrow_py/windows.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/golden/result_test/test_iter_pandas_async_materialize_1.jsonl
  sparrow-py/pytests/result_test.py
Labels: enhancement, sparrow, cla-signed

#640 feat: latched spread fallback
  crates/sparrow-runtime/src/execute/operation/spread.rs
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/golden/shift_by_test/test_shift_collect.jsonl
  sparrow-py/pytests/shift_by_test.py
Labels: enhancement, sparrow, cla-signed

#642 feat: Add union operation
  crates/sparrow-compiler/src/functions/collection.rs
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/list.rs
  crates/sparrow-instructions/src/evaluators/list/union.rs
  crates/sparrow-plan/src/inst.rs
  crates/sparrow-runtime/src/execute.rs
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/flatten_test.py
  sparrow-py/pytests/golden/flatten_test/test_flatten.jsonl
  sparrow-py/pytests/golden/union_test/test_union.jsonl
  sparrow-py/pytests/union_test.py
Labels: enhancement, sparrow, cla-signed

#646 fix: allow null strings in CSVs
  sparrow-py/pysrc/sparrow_py/sources/arrow.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/golden/length_test/test_length.jsonl
Labels: bug, cla-signed

#645 feat: Run simplifications in sparrow-py
  crates/sparrow-compiler/src/dfg/expr.rs
  crates/sparrow-main/tests/e2e/with_key_tests.rs
  crates/sparrow-session/src/session.rs
  sparrow-py/pytests/golden/with_key_test/test_with_key_last.jsonl
  sparrow-py/pytests/with_key_test.py
Labels: enhancement, sparrow, cla-signed

#647 feat: make collect continuous by setting interpolation
  crates/sparrow-compiler/src/plan/interpolations.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
Labels: enhancement, sparrow, cla-signed

#641 feat: trailing windows in collect for `DataType::Struct`
  crates/sparrow-arrow/src/concat_take.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/collect_struct_token.rs
  crates/sparrow-instructions/src/evaluators/list/collect_struct.rs
  sparrow-py/pysrc/sparrow_py/__init__.py
  sparrow-py/pysrc/sparrow_py/_result.py
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pysrc/sparrow_py/sources/__init__.py
  sparrow-py/pysrc/sparrow_py/sources/arrow.py
  sparrow-py/pysrc/sparrow_py/sources/source.py
  sparrow-py/pysrc/sparrow_py/windows.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/csv_string_source_test.py
  sparrow-py/pytests/flatten_test.py
  sparrow-py/pytests/golden/collect_test/test_collect_since_window.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_struct_trailing_window_1s.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_struct_trailing_window_3s.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_struct_trailing_window_3s_with_max.jsonl
  sparrow-py/pytests/golden/collect_test/test_collect_struct_trailing_window_3s_with_min.jsonl
  sparrow-py/pytests/jsonl_string_source_test.py
  sparrow-py/pytests/pandas_source_test.py
  sparrow-py/pytests/parquet_source_test.py
  sparrow-py/pytests/pylist_source_test.py
  sparrow-py/pytests/shift_by_test.py
  sparrow-py/pytests/source_test.py
  sparrow-py/pytests/timestream_test.py
  sparrow-py/pytests/union_test.py
  sparrow-py/pytests/with_key_test.py
Labels: enhancement, sparrow, cla-signed

#635 feat: use collect for lag in python builder
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/golden/lag_test/test_lag_list.jsonl
  sparrow-py/pytests/golden/lag_test/test_lag_struct.jsonl
  sparrow-py/pytests/golden/with_key_test/test_with_key_last.jsonl
  sparrow-py/pytests/lag_test.py
Labels: enhancement, cla-signed

#653 feat: Lambdas for building records/extending
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/golden/record_test/test_extend_input.jsonl
  sparrow-py/pytests/golden/shift_by_test/test_shift_collect.jsonl
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/shift_by_test.py
Labels: enhancement, cla-signed

#654 lint: Fix lint, mypy, etc.
  sparrow-py/noxfile.py
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pysrc/sparrow_py/sources/arrow.py
  sparrow-py/pysrc/sparrow_py/sources/source.py
  sparrow-py/pysrc/sparrow_py/windows.py
  sparrow-py/pytests/aggregation_test.py
  sparrow-py/pytests/collect_test.py
  sparrow-py/pytests/conftest.py
  sparrow-py/pytests/filter_test.py
  sparrow-py/pytests/if_test.py
  sparrow-py/pytests/lag_test.py
  sparrow-py/pytests/length_test.py
  sparrow-py/pytests/lookup_test.py
  sparrow-py/pytests/math_test.py
  sparrow-py/pytests/null_if_test.py
  sparrow-py/pytests/pandas_source_test.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/result_test.py
  sparrow-py/pytests/shift_by_test.py
  sparrow-py/pytests/shift_to_test.py
  sparrow-py/pytests/shift_until_test.py
  sparrow-py/pytests/source_test.py
  sparrow-py/pytests/time_of_test.py
  sparrow-py/pytests/time_test.py
  sparrow-py/pytests/timestream_test.py
  sparrow-py/pytests/udf_test.py
  sparrow-py/pytests/with_key_test.py
Labels: cla-signed

#657 fix: mypy again
  sparrow-py/docs/source/conf.py
  sparrow-py/poetry.lock
  sparrow-py/pyproject.toml
  sparrow-py/pysrc/sparrow_py/_timestream.py
  sparrow-py/pytests/record_test.py
  sparrow-py/pytests/shift_by_test.py
Labels: bug, cla-signed

#650 test: Verify pylist sources drop unneeded columns
  python/pytests/golden/pylist_source_test/test_read_pylist_ignore_column.jsonl
  python/pytests/golden/pylist_source_test/test_read_pylist_ignore_column_1.jsonl
  python/pytests/pylist_source_test.py
Labels: test, cla-signed

#658 feat: hack collect trailing with shift by
  crates/sparrow-instructions/src/evaluators/aggregation/token/collect_token.rs
  crates/sparrow-instructions/src/evaluators/list/collect_boolean.rs
  crates/sparrow-instructions/src/evaluators/list/collect_primitive.rs
  crates/sparrow-instructions/src/evaluators/list/collect_string.rs
  crates/sparrow-instructions/src/evaluators/list/collect_struct.rs
  python/pysrc/kaskada/_timestream.py
  python/pytests/collect_test.py
  python/pytests/golden/collect_test/test_collect_basic.jsonl
  python/pytests/golden/collect_test/test_collect_bool_trailing_window_1s.jsonl
  python/pytests/golden/collect_test/test_collect_bool_trailing_window_3s.jsonl
  python/pytests/golden/collect_test/test_collect_bool_trailing_window_3s_with_max.jsonl
  python/pytests/golden/collect_test/test_collect_bool_trailing_window_3s_with_min.jsonl
  python/pytests/golden/collect_test/test_collect_i64_trailing_window_1s.jsonl
  python/pytests/golden/collect_test/test_collect_i64_trailing_window_3s.jsonl
  python/pytests/golden/collect_test/test_collect_i64_trailing_window_3s_with_max.jsonl
  python/pytests/golden/collect_test/test_collect_i64_trailing_window_3s_with_min.jsonl
  python/pytests/golden/collect_test/test_collect_lists.jsonl
  python/pytests/golden/collect_test/test_collect_records.jsonl
  python/pytests/golden/collect_test/test_collect_records_field_ref.jsonl
  python/pytests/golden/collect_test/test_collect_since_window.jsonl
  python/pytests/golden/collect_test/test_collect_string_trailing_window_1s.jsonl
  python/pytests/golden/collect_test/test_collect_string_trailing_window_3s.jsonl
  python/pytests/golden/collect_test/test_collect_string_trailing_window_3s_with_max.jsonl
  python/pytests/golden/collect_test/test_collect_string_trailing_window_3s_with_min.jsonl
  python/pytests/golden/collect_test/test_collect_struct_trailing_window_1s.jsonl
  python/pytests/golden/collect_test/test_collect_struct_trailing_window_3s.jsonl
  python/pytests/golden/collect_test/test_collect_struct_trailing_window_3s_with_max.jsonl
  python/pytests/golden/collect_test/test_collect_struct_trailing_window_3s_with_min.jsonl
  python/pytests/golden/collect_test/test_collect_with_max.jsonl
  python/pytests/golden/collect_test/test_collect_with_min.jsonl
  python/pytests/golden/collect_test/test_collect_with_min_and_max.jsonl
Labels: enhancement, sparrow, cla-signed

#652 feat: add seconds_since timestamp_ns
  python/docs/source/reference/timestream/time.md
  python/pysrc/kaskada/_timestream.py
  python/pytests/golden/seconds_since_previous_test/test_seconds_since_previous.jsonl
  python/pytests/golden/seconds_since_test/test_seconds_since.jsonl
  python/pytests/golden/seconds_since_test/test_seconds_since_datetime.jsonl
  python/pytests/golden/seconds_since_test/test_seconds_since_int.jsonl
  python/pytests/golden/seconds_since_test/test_seconds_since_literal.jsonl
  python/pytests/pylist_source_test.py
  python/pytests/seconds_since_previous_test.py
  python/pytests/seconds_since_test.py
Labels: enhancement, cla-signed

#660 feat: add count aggregation
  python/docs/source/reference/timestream/aggregation.md
  python/pysrc/kaskada/_timestream.py
  python/pytests/aggregation/count_test.py
  python/pytests/aggregation/sum_test.py
  python/pytests/conftest.py
  python/pytests/golden/count_test/test_count_since_true.jsonl
  python/pytests/golden/count_test/test_count_unwindowed.jsonl
  python/pytests/golden/count_test/test_count_windowed.jsonl
  python/pytests/golden/sum_test/test_sum_since_true.jsonl
  python/pytests/golden/sum_test/test_sum_unwindowed.jsonl
  python/pytests/golden/sum_test/test_sum_windowed.jsonl
Labels: enhancement, cla-signed

#663 bug: fix is_null to use not_ instead of neg
  python/pysrc/kaskada/_timestream.py
  python/pytests/golden/null_test/test_is_null.jsonl
  python/pytests/golden/null_test/test_null_if.jsonl
  python/pytests/null_test.py
Labels: bug, cla-signed

#668 docs: Stub more doc content
  python/docs/source/concepts.md
  python/docs/source/conf.py
  python/docs/source/guide/aggregation.md
  python/docs/source/guide/data_types.md
  python/docs/source/guide/entities.md
  python/docs/source/guide/index.md
  python/docs/source/guide/installation.md
  python/docs/source/guide/joins.md
  python/docs/source/guide/sources.md
  python/docs/source/guide/timestreams.md
  python/docs/source/index.md
  python/docs/source/quickstart.md
  python/docs/source/reference/timestream/index.md
  python/docs/source/tour.md
  python/docs/source/why.md
  python/noxfile.py
Labels: documentation, cla-signed

#671 feat: add else call
  python/docs/source/reference/timestream/misc.md
  python/pysrc/kaskada/_timestream.py
  python/pytests/conftest.py
  python/pytests/else_test.py
  python/pytests/golden/else_test/test_else_.jsonl
  python/pytests/golden/null_test/test_is_null.jsonl
  python/pytests/pandas_source_test.py
Labels: enhancement, cla-signed

#670 ref: remove signature modes
  crates/sparrow-compiler/src/dfg.rs
  crates/sparrow-compiler/src/dfg/const_eval.rs
  crates/sparrow-compiler/src/plan/expression_to_plan.rs
  crates/sparrow-compiler/src/types/instruction.rs
  crates/sparrow-instructions/src/inst.rs
Labels: sparrow, refactor, cla-signed

#676 feat: Warn when using `==` or `!=` on timestreams
  python/pysrc/kaskada/_timestream.py
  python/pytests/else_test.py
  python/pytests/timestream_test.py
Labels: enhancement, cla-signed

#673 feat: Support plotting of Timestream objects
  crates/sparrow-compiler/src/time_domain.rs
  crates/sparrow-session/src/expr.rs
  python/Cargo.lock
  python/poetry.lock
  python/pyproject.toml
  python/pysrc/kaskada/__init__.py
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/plot.py
  python/src/expr.rs
  python/visualize.ipynb
Labels: enhancement, sparrow, cla-signed

#677 bug: add test for else with records
  python/pytests/else_test.py
  python/pytests/golden/else_test/test_else_debug.jsonl
Labels: bug, cla-signed

#661 ci: Stub out CI for new python package
  .github/workflows/ci_python.yml
  python/Cargo.lock
  python/Cargo.toml
  python/mypy.ini
  python/noxfile.py
  python/poetry.lock
  python/pyproject.toml
  python/pysrc/kaskada/__init__.py
  python/pysrc/kaskada/_result.py
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/plot.py
  python/pysrc/kaskada/sources/source.py
  python/pytests/aggregation/count_if_test.py
  python/pytests/aggregation/count_test.py
  python/pytests/aggregation/max_test.py
  python/pytests/aggregation/mean_test.py
  python/pytests/aggregation/min_test.py
  python/pytests/aggregation/stddev_test.py
  python/pytests/aggregation/sum_test.py
  python/pytests/aggregation/variance_test.py
  python/src/lib.rs
Labels: sparrow, build, cla-signed

#679 ci: fix conditions
  .github/workflows/ci_python.yml
Labels: build, cla-signed

#680 docs: Remove home page from menu (can click logo)
  python/docs/source/conf.py
  python/docs/source/index.md
  python/noxfile.py
Labels: documentation, cla-signed

#665 ref: rename time_of to time
  python/docs/source/reference/timestream/time.md
  python/pysrc/kaskada/_timestream.py
  python/pytests/golden/time_test/test_time_of_point.jsonl
  python/pytests/shift_to_test.py
  python/pytests/time_of_test.py
  python/pytests/time_test.py
Labels: refactor, cla-signed

#683 Edit the front page a bit.
  python/docs/source/index.md
Labels: cla-signed

#684 Add google tracking to Sphynx docs
  python/docs/source/conf.py
Labels: cla-signed

#678 Add time-centric example notebook
  python/docs/source/examples/index.md
  python/docs/source/examples/time_centric.ipynb
  python/docs/source/reference/sources.md
  python/noxfile.py
Labels: cla-signed

#685 feat: Setup release process
  .github/release-drafter-python-client.yml
  .github/release-drafter-python.yml
  .github/workflows/ci_python.yml
  .github/workflows/release_drafter.yml
  python/docs/source/conf.py
  python/pyproject.toml
  scripts/get_version.py
  scripts/set_versions.py
Labels: enhancement, build, cla-signed

#690 ci: fix versioning; enable publishing
  .github/workflows/ci_python.yml
  scripts/get_version.py
Labels: build, cla-signed

#692 ci: Split CI and release workflows
  .github/workflows/ci_python.yml
  .github/workflows/release_python.yml
Labels: build, cla-signed

#687 docs: Fix link and logos
  python/docs/source/_static/kaskada-negative.svg
  python/docs/source/_static/kaskada-positive.svg
  python/docs/source/_static/kaskada.svg
  python/docs/source/conf.py
  python/noxfile.py
Labels: documentation, cla-signed

#700 ci: re-install Kaskada when building docs
  .github/workflows/ci_python.yml
Labels: build, cla-signed

#694 chore: Fixes / notes on release process
  .github/release-drafter-python.yml
  .github/workflows/release_python.yml
Labels: build, cla-signed

#699 docs: Omit page-TOC for single-page docs
  python/docs/source/_templates/autosummary/class.rst
  python/docs/source/_templates/autosummary/function.rst
  python/docs/source/_templates/autosummary/method.rst
  python/docs/source/reference/timestream/index.md
  python/noxfile.py
Labels: documentation, cla-signed

#681 feat: udf node creation in dfg
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/dfg.rs
  crates/sparrow-compiler/src/functions.rs
  crates/sparrow-compiler/src/functions/time_domain_check.rs
  crates/sparrow-compiler/src/types/instruction.rs
  crates/sparrow-instructions/src/inst.rs
  crates/sparrow-session/src/session.rs
  python/mypy.ini
  python/pysrc/kaskada/_timestream.py
  python/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#704 Update conf.py
  python/docs/source/conf.py
Labels: cla-signed

#705 docs: fix logo in hero
  python/docs/source/index.md
Labels: documentation, cla-signed

#702 feat: Expose tick functions
  crates/sparrow-api/src/kaskada/v1alpha/prepared_file_impl.rs
  crates/sparrow-api/src/kaskada/v1alpha/schema_traits.rs
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-execution/src/lib.rs
  crates/sparrow-expressions/src/evaluators/record.rs
  crates/sparrow-expressions/src/values.rs
  crates/sparrow-qfr-tool/src/chrome/conversion.rs
  crates/sparrow-session/src/session.rs
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/windows.py
  python/pytests/aggregation/sum_test.py
  python/pytests/ceil_test.py
  python/pytests/clamp_test.py
  python/pytests/coalesce_test.py
  python/pytests/exp_test.py
  python/pytests/floor_test.py
  python/pytests/golden/sum_test/test_sum_since_hourly.jsonl
  python/pytests/powf_test.py
Labels: enhancement, sparrow, cla-signed

#703 feat: python udf implementation
  Cargo.lock
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/plan/expression_to_plan.rs
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/compute_executor.rs
  crates/sparrow-runtime/src/execute/operation.rs
  crates/sparrow-runtime/src/execute/operation/expression_executor.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/execute/operation/testing.rs
  crates/sparrow-session/Cargo.toml
  crates/sparrow-session/src/session.rs
  python/.vscode/settings.json
  python/Cargo.lock
  python/Cargo.toml
  python/pysrc/kaskada/__init__.py
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/udf.py
  python/pytests/golden/udf_test/test_add_udf_direct.jsonl
  python/pytests/golden/udf_test/test_add_udf_pipe.jsonl
  python/pytests/udf_test.py
  python/src/execution.rs
  python/src/expr.rs
  python/src/lib.rs
  python/src/udf.rs
Labels: enhancement, sparrow, cla-signed

#708 docs: Review data types
  .github/workflows/ci_python.yml
  python/docs/source/examples/time_centric.ipynb
  python/docs/source/guide/data_types.md
  python/docs/source/reference/timestream/index.md
  python/docs/source/reference/timestream/misc.md
Labels: documentation, build, cla-signed

#707 ref: Make parameters to sources explicit
  python/CHANGELOG.md
  python/docs/source/examples/time_centric.ipynb
  python/docs/source/index.md
  python/docs/source/quickstart.md
  python/docs/source/tour.md
  python/poetry.lock
  python/pyproject.toml
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/sources/arrow.py
  python/pysrc/kaskada/sources/source.py
  python/pytests/aggregation/count_if_test.py
  python/pytests/aggregation/count_test.py
  python/pytests/aggregation/max_test.py
  python/pytests/aggregation/mean_test.py
  python/pytests/aggregation/min_test.py
  python/pytests/aggregation/stddev_test.py
  python/pytests/aggregation/sum_test.py
  python/pytests/aggregation/variance_test.py
  python/pytests/ceil_test.py
  python/pytests/clamp_test.py
  python/pytests/coalesce_test.py
  python/pytests/collect_test.py
  python/pytests/csv_string_source_test.py
  python/pytests/else_test.py
  python/pytests/exp_test.py
  python/pytests/filter_test.py
  python/pytests/flatten_test.py
  python/pytests/floor_test.py
  python/pytests/if_test.py
  python/pytests/jsonl_string_source_test.py
  python/pytests/lag_test.py
  python/pytests/length_test.py
  python/pytests/lookup_test.py
  python/pytests/math_test.py
  python/pytests/null_test.py
  python/pytests/pandas_source_test.py
  python/pytests/parquet_source_test.py
  python/pytests/powf_test.py
  python/pytests/pylist_source_test.py
  python/pytests/record_test.py
  python/pytests/result_test.py
  python/pytests/seconds_since_previous_test.py
  python/pytests/seconds_since_test.py
  python/pytests/shift_by_test.py
  python/pytests/shift_to_test.py
  python/pytests/shift_until_test.py
  python/pytests/source_test.py
  python/pytests/time_test.py
  python/pytests/timestream_test.py
  python/pytests/udf_test.py
  python/pytests/union_test.py
  python/pytests/with_key_test.py
  python/src/table.rs
  python/visualize.ipynb
Labels: refactor, cla-signed

#710 echo versions in python release
  .github/workflows/release_python.yml
Labels: build, cla-signed

#711 bug: remove extra quote
  .github/workflows/release_python.yml
Labels: bug, build, cla-signed

#712 docs: Change to Google Doc Style
  .github/workflows/ci_python.yml
  python/.darglint
  python/Cargo.toml
  python/docs/source/conf.py
  python/docs/source/examples/time_centric.ipynb
  python/docs/source/index.md
  python/docs/source/reference/timestream/aggregation.md
  python/docs/source/reference/timestream/arithmetic.md
  python/docs/source/reference/timestream/collection.md
  python/docs/source/reference/timestream/comparison.md
  python/docs/source/reference/timestream/index.md
  python/docs/source/reference/timestream/misc.md
  python/docs/source/reference/timestream/records.md
  python/docs/source/reference/windows.md
  python/noxfile.py
  python/poetry.lock
  python/pyproject.toml
  python/pysrc/kaskada/__init__.py
  python/pysrc/kaskada/_execution.py
  python/pysrc/kaskada/_result.py
  python/pysrc/kaskada/_session.py
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/plot.py
  python/pysrc/kaskada/sources/arrow.py
  python/pysrc/kaskada/windows.py
Labels: documentation, sparrow, build, cla-signed

#715 docs: Start fleshing out documentation on timestreams
  python/Cargo.lock
  python/docs/source/guide/aggregation.md
  python/docs/source/guide/sources.md
  python/docs/source/guide/timestreams.md
  python/docs/source/reference/timestream/aggregation.md
  python/docs/source/reference/timestream/collection.md
  python/pysrc/kaskada/plot.py
Labels: documentation, sparrow, cla-signed

#718 bug: fix hashing of udfs
  crates/sparrow-instructions/src/udf.rs
  python/pytests/golden/udf_test/test_add_udf_redefined_inline.jsonl
  python/pytests/udf_test.py
Labels: bug, sparrow, cla-signed

#721 release: Install wheels by path
  .github/workflows/ci_python.yml
  .github/workflows/release_python.yml
  scripts/get_version.py
  scripts/set_versions.py
  scripts/version.py
Labels: build, release, cla-signed

#724 docs: Edit Wren's readme
  wren/README.md
Labels: documentation, wren, cla-signed

#706 feat: Introduce crate for standalone signatures
  Cargo.lock
  Cargo.toml
  crates/sparrow-types/Cargo.toml
  crates/sparrow-types/src/error.rs
  crates/sparrow-types/src/fenl_type.rs
  crates/sparrow-types/src/instantiate.rs
  crates/sparrow-types/src/instantiate/least_upper_bound.rs
  crates/sparrow-types/src/instantiate/type_constraints.rs
  crates/sparrow-types/src/lib.rs
  crates/sparrow-types/src/signature.rs
  crates/sparrow-types/src/signature/parser.rs
  crates/sparrow-types/src/type_class.rs
Labels: enhancement, sparrow, cla-signed

#727 lint: Allow multiple imports per line
  python/docs/source/_extensions/gallery_directive.py
  python/docs/source/conf.py
  python/pyproject.toml
  python/pysrc/kaskada/__init__.py
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/_result.py
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/sources/__init__.py
  python/pysrc/kaskada/sources/arrow.py
  python/pysrc/kaskada/sources/source.py
  python/pysrc/kaskada/udf.py
  python/pytests/shift_to_test.py
Labels: cla-signed

#720 docs: First pass fleshing out the user guide
  python/docs/source/conf.py
  python/docs/source/guide/aggregation.md
  python/docs/source/guide/entities.md
  python/docs/source/guide/execution.md
  python/docs/source/guide/index.md
  python/docs/source/guide/installation.md
  python/docs/source/guide/joins.md
  python/docs/source/guide/timestreams.md
  python/docs/source/quickstart.md
  python/poetry.lock
  python/pyproject.toml
  python/pysrc/kaskada/plot.py
Labels: documentation, cla-signed

#728 feat: introduce new execution API
  crates/sparrow-session/src/execution.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-session/src/table.rs
  python/docs/source/guide/execution.md
  python/docs/source/guide/index.md
  python/docs/source/index.md
  python/docs/source/quickstart.md
  python/docs/source/reference/destinations.md
  python/docs/source/reference/execution.md
  python/docs/source/reference/results.md
  python/docs/source/reference/timestream/execution.md
  python/docs/source/reference/timestream/index.md
  python/noxfile.py
  python/pyproject.toml
  python/pysrc/kaskada/__init__.py
  python/pysrc/kaskada/_execution.py
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/_result.py
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/destinations.py
  python/pysrc/kaskada/plot.py
  python/pysrc/kaskada/results.py
  python/pysrc/kaskada/udf.py
  python/pytests/conftest.py
  python/pytests/golden/result_test/test_iter_pandas_async_live.jsonl
  python/pytests/golden/result_test/test_iter_pandas_async_live_1.jsonl
  python/pytests/result_test.py
  python/src/execution.rs
Labels: enhancement, sparrow, refactor, cla-signed
