Repository kaskada-ai/kaskada, pull requests merged in 2023-09, with the labels that each got.

#732 docs: Use pydata theme and setup ablog
  .github/workflows/ci_python.yml
  .github/workflows/release_python.yml
  python/docs/source/_layouts/default.yml
  python/docs/source/blog/index.md
  python/docs/source/blog/posts/2023-03-28-announcing-kaskada-oss.md
  python/docs/source/blog/posts/2023-08-25-new-kaskada.md
  python/docs/source/conf.py
  python/docs/source/examples/index.md
  python/docs/source/guide/index.md
  python/docs/source/guide/quickstart.md
  python/docs/source/guide/tour.md
  python/docs/source/guide/why.md
  python/docs/source/index.md
  python/docs/source/reference/index.md
  python/noxfile.py
  python/poetry.lock
  python/pyproject.toml
Labels: documentation, sparrow, build, cla-signed

#723 implemented numerous existing operations
  python/docs/source/reference/timestream/arithmetic.md
  python/docs/source/reference/timestream/index.md
  python/docs/source/reference/timestream/misc.md
  python/docs/source/reference/timestream/string.md
  python/noxfile.py
  python/pysrc/kaskada/_timestream.py
  python/pytests/golden/greatest_test/test_greatest.jsonl
  python/pytests/golden/hash_test/test_hash_integer.jsonl
  python/pytests/golden/hash_test/test_hash_string.jsonl
  python/pytests/golden/least_test/test_least.jsonl
  python/pytests/golden/lower_test/test_lower.jsonl
  python/pytests/golden/round_test/test_round.jsonl
  python/pytests/golden/sqrt_test/test_sqrt.jsonl
  python/pytests/golden/upper_test/test_upper.jsonl
  python/pytests/greatest_test.py
  python/pytests/hash_test.py
  python/pytests/least_test.py
  python/pytests/lower_test.py
  python/pytests/round_test.py
  python/pytests/sqrt_test.py
  python/pytests/upper_test.py
Labels: cla-signed

#735 Adding example showing real-time event handling from API requests
  examples/event-api/README.md
  examples/event-api/server.py
Labels: cla-signed

#578 docs: add basic list example notebook
  examples/collection_types/List Types.ipynb
  examples/collection_types/data_with_list.parquet
Labels: documentation, cla-signed

#736 bug: fix set version release script
  scripts/version.py
Labels: bug, cla-signed

#737 bug: fix normalization of versions when setting toml
  .github/workflows/release_python.yml
  scripts/version.py
Labels: bug, build, cla-signed

#731 feat: allow comparisons against literal timedeltas
  Cargo.lock
  crates/sparrow-compiler/src/types/inference.rs
  crates/sparrow-instructions/Cargo.toml
  crates/sparrow-instructions/src/evaluators/cast.rs
  crates/sparrow-instructions/src/evaluators/macros.rs
  crates/sparrow-main/tests/e2e/comparison_tests.rs
  crates/sparrow-session/src/expr.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-syntax/src/syntax/literal.rs
  python/Cargo.lock
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/_timestream.py
  python/pytests/golden/time_test/test_compare_literal_timedelta.jsonl
  python/pytests/golden/time_test/test_time_add_days.jsonl
  python/pytests/golden/time_test/test_time_add_days_and_minutes.jsonl
  python/pytests/golden/time_test/test_time_add_hours.jsonl
  python/pytests/golden/time_test/test_time_add_minutes.jsonl
  python/pytests/golden/time_test/test_time_add_seconds.jsonl
  python/pytests/golden/time_test/test_time_of_point.jsonl
  python/pytests/time_test.py
  python/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#738 pip install tomlkit in release
  .github/workflows/release_python.yml
Labels: cla-signed

#739 comment out arm64 wheel target
  .github/workflows/release_python.yml
Labels: build, cla-signed

#733 feat: Add support for results and time ranges
  crates/sparrow-compiler/src/frontend.rs
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/operation/expression_executor.rs
  crates/sparrow-session/src/lib.rs
  crates/sparrow-session/src/session.rs
  python/pysrc/kaskada/__init__.py
  python/pysrc/kaskada/_execution.py
  python/pysrc/kaskada/_timestream.py
  python/pytests/conftest.py
  python/pytests/execution_test.py
  python/pytests/golden/execution_test/test_history.jsonl
  python/pytests/golden/execution_test/test_history_1.jsonl
  python/pytests/golden/execution_test/test_history_2.jsonl
  python/pytests/golden/execution_test/test_history_3.jsonl
  python/pytests/golden/execution_test/test_iter_pandas.jsonl
  python/pytests/golden/execution_test/test_iter_pandas_1.jsonl
  python/pytests/golden/execution_test/test_iter_pandas_async.jsonl
  python/pytests/golden/execution_test/test_iter_pandas_async_1.jsonl
  python/pytests/golden/execution_test/test_iter_pandas_async_live.jsonl
  python/pytests/golden/execution_test/test_iter_pandas_async_live_1.jsonl
  python/pytests/golden/execution_test/test_snapshot.jsonl
  python/pytests/golden/execution_test/test_snapshot_1.jsonl
  python/pytests/golden/execution_test/test_snapshot_2.jsonl
  python/src/expr.rs
Labels: enhancement, sparrow, cla-signed

#741 add missing quotation in release announcement
  .github/workflows/release_python.yml
Labels: build, cla-signed

#740 docs: Minor fixes to blogs
  python/docs/source/blog/index.md
  python/docs/source/blog/posts/2023-03-28-announcing-kaskada-oss.md
  python/docs/source/blog/posts/2023-08-25-new-kaskada.md
  python/docs/source/conf.py
Labels: documentation, cla-signed

#744 feat: Configurable retention on PyDict sources
  crates/sparrow-merge/src/in_memory_batches.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-session/src/table.rs
  examples/event-api/server.py
  python/docs/source/conf.py
  python/docs/source/index.md
  python/docs/source/reference/sources.md
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/sources/__init__.py
  python/pysrc/kaskada/sources/arrow.py
  python/pysrc/kaskada/sources/source.py
  python/pytests/aggregation/sum_test.py
  python/pytests/execution_test.py
  python/pytests/flatten_test.py
  python/pytests/golden/pydict_source_test/test_read_pydict.jsonl
  python/pytests/golden/pydict_source_test/test_read_pydict_1.jsonl
  python/pytests/golden/pydict_source_test/test_read_pydict_2.jsonl
  python/pytests/golden/pydict_source_test/test_read_pydict_ignore_column.jsonl
  python/pytests/golden/pydict_source_test/test_read_pydict_ignore_column_1.jsonl
  python/pytests/golden/pydict_source_test/test_read_pydict_lists.jsonl
  python/pytests/golden/pydict_source_test/test_read_pydict_lists_1.jsonl
  python/pytests/pydict_source_test.py
  python/pytests/union_test.py
  python/src/table.rs
Labels: enhancement, sparrow, cla-signed

#745 fix: Live executions with an empty PyDict
  crates/sparrow-merge/src/in_memory_batches.rs
  crates/sparrow-runtime/src/execute/operation/merge.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/execute/operation/tick.rs
  crates/sparrow-runtime/src/key_hash_inverse.rs
  python/pysrc/kaskada/_timestream.py
  python/pytests/golden/pydict_source_test/test_read_pydict_empty_live.jsonl
  python/pytests/pydict_source_test.py
Labels: bug, sparrow, cla-signed

#747 Clean up example script
  examples/event-api/server.py
Labels: cla-signed

#742 ref: remove unused file
  crates/sparrow-compiler/src/table_content.rs
Labels: sparrow, refactor, cla-signed

#752 tweaks to bluesky example
  python/docs/source/examples/bluesky.md
  python/docs/source/examples/bluesky.py
  python/docs/source/examples/index.md
Labels: cla-signed

#751 Add an example showing how to consume from BlueSky
  python/docs/source/examples/bluesky.md
  python/docs/source/examples/bluesky.py
  python/docs/source/examples/index.md
  python/poetry.lock
  python/pyproject.toml
Labels: cla-signed

#753 Update pyproject.toml
  python/pyproject.toml
Labels: cla-signed

#750 Doc fixes to align to new API and release versions
  python/docs/source/guide/index.md
  python/docs/source/guide/installation.md
  python/docs/source/guide/quickstart.md
  python/noxfile.py
  python/requirements-dev.txt
Labels: cla-signed

#755 ref: replace first/last with generic aggregators
  crates/sparrow-compiler/src/functions.rs
  crates/sparrow-compiler/src/functions/aggregation.rs
  crates/sparrow-compiler/src/functions/implementation.rs
  crates/sparrow-compiler/src/functions/pushdown.rs
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__projection_pushdown.snap
  crates/sparrow-instructions/src/evaluators.rs
  crates/sparrow-instructions/src/evaluators/aggregation.rs
  crates/sparrow-instructions/src/evaluators/aggregation/boolean.rs
  crates/sparrow-instructions/src/evaluators/aggregation/boolean/first_boolean_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/boolean/last_boolean_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/boolean/two_stacks_first_boolean_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/boolean/two_stacks_last_boolean_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/first_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/function.rs
  crates/sparrow-instructions/src/evaluators/aggregation/function/boolean_agg_fn.rs
  crates/sparrow-instructions/src/evaluators/aggregation/function/primitive_agg_fn.rs
  crates/sparrow-instructions/src/evaluators/aggregation/function/string_agg_fn.rs
  crates/sparrow-instructions/src/evaluators/aggregation/last_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/list.rs
  crates/sparrow-instructions/src/evaluators/aggregation/list/first_list_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/list/last_list_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/map.rs
  crates/sparrow-instructions/src/evaluators/aggregation/map/first_map_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/map/last_map_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/primitive/arrow_agg_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/primitive/two_stacks_arrow_agg_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/string.rs
  crates/sparrow-instructions/src/evaluators/aggregation/string/first_string_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/string/last_string_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/string/two_stacks_first_string_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/string/two_stacks_last_string_evaluator.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/array_ref_accum_token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/boolean_accum_token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/list_accum_token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/string_accum_token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/two_stacks_boolean_accum_token.rs
  crates/sparrow-instructions/src/evaluators/aggregation/token/two_stacks_string_accum_token.rs
  crates/sparrow-main/tests/e2e/aggregation_tests.rs
  crates/sparrow-main/tests/e2e/windowed_aggregation_tests.rs
Labels: sparrow, refactor, cla-signed

#749 feat: add parquet source to python ffi
  Cargo.lock
  crates/sparrow-compiler/Cargo.toml
  crates/sparrow-compiler/src/data_context.rs
  crates/sparrow-merge/src/in_memory_batches.rs
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/key_hash_inverse.rs
  crates/sparrow-runtime/src/lib.rs
  crates/sparrow-runtime/src/prepare/preparer.rs
  crates/sparrow-runtime/src/read/table_reader.rs
  crates/sparrow-runtime/src/stores/registry.rs
  crates/sparrow-session/src/error.rs
  crates/sparrow-session/src/session.rs
  crates/sparrow-session/src/table.rs
  python/Cargo.lock
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/sources/arrow.py
  python/pysrc/kaskada/sources/source.py
  python/src/execution.rs
  python/src/table.rs
Labels: enhancement, sparrow, cla-signed

#760 ref: remove print in parquet source method
  python/pysrc/kaskada/sources/arrow.py
Labels: refactor, cla-signed

#748 release: fix publishing announcement
  .github/workflows/release_python.yml
Labels: build, release, cla-signed

#757 Add an example reading from Reddit
  python/docs/source/examples/index.md
  python/docs/source/examples/reddit.md
  python/docs/source/examples/reddit.py
Labels: cla-signed

#764 locked python client to engine@v0.11.0
  clients/python/pyproject.toml
  clients/python/src/kaskada/api/release.py
  clients/python/src/kaskada/api/session.py
  clients/python/tests/api/test_session.py
Labels: python, cla-signed

#767 added substring, json, len, is_valid methods
  python/docs/source/reference/timestream/string.md
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/sources/arrow.py
  python/pytests/golden/len_test/test_len.jsonl
  python/pytests/golden/substring_test/test_substring.jsonl
  python/pytests/len_test.py
  python/pytests/substring_test.py
Labels: cla-signed

#758 feat: allow periodic filtering of aggregations using a tumbling window
  crates/sparrow-compiler/src/ast_to_dfg.rs
  crates/sparrow-compiler/src/plan/interpolations.rs
  crates/sparrow-compiler/src/plan/transform_to_plan.rs
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__basic_sum.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__basic_sum_when_aggregate.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__basic_sum_when_event.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__count_since_window.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__lookup_diff_grouping.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__lookup_same_grouping.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__lookup_same_grouping_with_slicing.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__projection_pushdown.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__since_daily.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__since_daily_multiple_passes.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__tab_characters_are_allowed.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__unexported.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__with_key.snap
  crates/sparrow-compiler/tests/snapshots/compiler_golden_tests__with_key_default_grouping.snap
  crates/sparrow-main/tests/e2e/collect_tests.rs
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/windows.py
  python/pytests/aggregation/count_if_test.py
  python/pytests/aggregation/count_test.py
  python/pytests/aggregation/max_test.py
  python/pytests/aggregation/mean_test.py
  python/pytests/aggregation/min_test.py
  python/pytests/aggregation/stddev_test.py
  python/pytests/aggregation/sum_test.py
  python/pytests/aggregation/variance_test.py
  python/pytests/filter_test.py
  python/pytests/golden/count_if_test/test_count_if_since_true.jsonl
  python/pytests/golden/count_if_test/test_count_if_windowed.jsonl
  python/pytests/golden/count_test/test_count_since_true.jsonl
  python/pytests/golden/count_test/test_count_sliding.jsonl
  python/pytests/golden/count_test/test_count_windowed.jsonl
  python/pytests/golden/filter_test/test_filter_to_merge_preserves_interpolation.jsonl
  python/pytests/golden/filter_test/test_if_filter_n.jsonl
  python/pytests/golden/max_test/test_max_since_true.jsonl
  python/pytests/golden/max_test/test_max_windowed.jsonl
  python/pytests/golden/mean_test/test_mean_since_true.jsonl
  python/pytests/golden/mean_test/test_mean_windowed.jsonl
  python/pytests/golden/min_test/test_min_windowed.jsonl
  python/pytests/golden/shift_until_test/test_shift_until_predicate.jsonl
  python/pytests/golden/stddev_test/test_stddev_since_true.jsonl
  python/pytests/golden/stddev_test/test_stddev_windowed.jsonl
  python/pytests/golden/sum_test/test_sum_since_true.jsonl
  python/pytests/golden/sum_test/test_sum_tumbling_hourly.jsonl
  python/pytests/golden/sum_test/test_sum_tumbling_predicate.jsonl
  python/pytests/golden/sum_test/test_sum_windowed.jsonl
  python/pytests/golden/variance_test/test_variance_since_true.jsonl
  python/pytests/golden/variance_test/test_variance_windowed.jsonl
Labels: enhancement, sparrow, cla-signed

#765 release: Mark as latest
  .github/workflows/release_python.yml
Labels: build, release, cla-signed

#769 docs: fix typo in docs
  python/pysrc/kaskada/_timestream.py
Labels: documentation, cla-signed

#770 bug: fix shift to batch bounds
  crates/sparrow-runtime/src/execute/operation/shift_to.rs
  python/pytests/golden/shift_by_test/test_filter_to_shift.jsonl
  python/pytests/shift_by_test.py
Labels: bug, sparrow, cla-signed

#771 fixed issue when subsort is provided
  crates/sparrow-runtime/src/prepare/preparer.rs
  python/pytests/csv_string_source_test.py
  python/pytests/golden/csv_string_source_test/test_read_csv_with_subsort.jsonl
  python/pytests/golden/csv_string_source_test/test_read_csv_with_subsort_1.jsonl
  python/pytests/golden/jsonl_string_source_test/test_read_jsonl_with_subsort.jsonl
  python/pytests/golden/jsonl_string_source_test/test_read_jsonl_with_subsort_1.jsonl
  python/pytests/golden/pandas_source_test/test_add_dataframe_with_subsort.jsonl
  python/pytests/golden/pandas_source_test/test_add_dataframe_with_subsort_1.jsonl
  python/pytests/golden/parquet_source_test/test_read_parquet_with_subsort.jsonl
  python/pytests/golden/parquet_source_test/test_read_parquet_with_subsort_1.jsonl
  python/pytests/jsonl_string_source_test.py
  python/pytests/pandas_source_test.py
  python/pytests/parquet_source_test.py
Labels: sparrow, cla-signed

#773 added new jsonl-file source
  python/docs/source/reference/sources.md
  python/pysrc/kaskada/sources/__init__.py
  python/pysrc/kaskada/sources/arrow.py
  python/pysrc/kaskada/sources/source.py
  python/pytests/golden/jsonl_file_source_test/test_read_jsonl_file.jsonl
  python/pytests/golden/jsonl_file_source_test/test_read_jsonl_file_1.jsonl
  python/pytests/golden/jsonl_file_source_test/test_read_jsonl_file_with_subsort.jsonl
  python/pytests/golden/jsonl_file_source_test/test_read_jsonl_file_with_subsort_1.jsonl
  python/pytests/jsonl_file_source_test.py
  testdata/purchases/purchases_part1.jsonl
  testdata/purchases/purchases_part2.jsonl
Labels: cla-signed

#778 ref: use new prepare code and remove some old
  crates/sparrow-main/tests/e2e/aggregation_tests.rs
  crates/sparrow-main/tests/e2e/cast_tests.rs
  crates/sparrow-main/tests/e2e/coalesce_tests.rs
  crates/sparrow-main/tests/e2e/collect_tests.rs
  crates/sparrow-main/tests/e2e/comparison_tests.rs
  crates/sparrow-main/tests/e2e/decoration_tests.rs
  crates/sparrow-main/tests/e2e/entity_key_output_tests.rs
  crates/sparrow-main/tests/e2e/equality_tests.rs
  crates/sparrow-main/tests/e2e/formula_tests.rs
  crates/sparrow-main/tests/e2e/general_tests.rs
  crates/sparrow-main/tests/e2e/json_tests.rs
  crates/sparrow-main/tests/e2e/logical_tests.rs
  crates/sparrow-main/tests/e2e/lookup_tests.rs
  crates/sparrow-main/tests/e2e/math_tests.rs
  crates/sparrow-main/tests/e2e/multiple_tables.rs
  crates/sparrow-main/tests/e2e/notebooks/event_data_tests.rs
  crates/sparrow-main/tests/e2e/parquet_tests.rs
  crates/sparrow-main/tests/e2e/prepare_tests.rs
  crates/sparrow-main/tests/e2e/record_tests.rs
  crates/sparrow-main/tests/e2e/shift_tests.rs
  crates/sparrow-main/tests/e2e/string_tests.rs
  crates/sparrow-main/tests/e2e/tick_tests.rs
  crates/sparrow-main/tests/e2e/time_tests.rs
  crates/sparrow-main/tests/e2e/when_tests.rs
  crates/sparrow-main/tests/e2e/windowed_aggregation_tests.rs
  crates/sparrow-main/tests/e2e/with_key_tests.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/prepare/column_behavior.rs
  crates/sparrow-runtime/src/prepare/execute_input_stream.rs
  crates/sparrow-runtime/src/prepare/prepare_input_stream.rs
  crates/sparrow-runtime/src/prepare/preparer.rs
Labels: sparrow, refactor, cla-signed

#763 bug: drains output channel when batching results
  crates/sparrow-runtime/src/execute/output.rs
  crates/sparrow-session/src/execution.rs
  crates/sparrow-session/src/session.rs
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/sources/__init__.py
  python/pysrc/kaskada/sources/arrow.py
  python/pysrc/kaskada/sources/source.py
  python/pytests/filter_test.py
  python/pytests/golden/parquet_source_test/test_large_parquet_file.jsonl
  python/pytests/len_test.py
  python/pytests/parquet_source_test.py
  testdata/parquet/purchases_100k.parquet
Labels: bug, sparrow, cla-signed

#780 feat: Expose DFG and query plans on Timestream
  crates/sparrow-compiler/src/dfg.rs
  crates/sparrow-compiler/src/dfg/expr.rs
  crates/sparrow-compiler/src/lib.rs
  crates/sparrow-session/src/lib.rs
  crates/sparrow-session/src/session.rs
  python/docs/source/examples/bluesky.py
  python/docs/source/examples/reddit.py
  python/mypy.ini
  python/poetry.lock
  python/pyproject.toml
  python/pysrc/kaskada/_execution.py
  python/pysrc/kaskada/_ffi.pyi
  python/pysrc/kaskada/_timestream.py
  python/pysrc/kaskada/sources/arrow.py
  python/src/expr.rs
Labels: enhancement, sparrow, cla-signed
