Repository kaskada-ai/kaskada, pull requests merged in 2023-05, with the labels that each got.

#293 bug: add ignored test for unexpected non-null when behavior
  crates/sparrow-main/tests/e2e/when_tests.rs
Labels: bug, sparrow

#231 Object Store for FileService and PrepareService
  crates/sparrow-main/src/prepare.rs
  crates/sparrow-main/src/serve.rs
  crates/sparrow-main/src/serve/preparation_service.rs
  crates/sparrow-runtime/src/metadata/prepared_metadata.rs
  crates/sparrow-runtime/src/metadata/raw_metadata.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/prepare/error.rs
  crates/sparrow-runtime/src/stores/object_store_url.rs
  crates/sparrow-runtime/src/stores/object_stores.rs
  examples/Querying from GCP.ipynb
  wren/client/object_store_client.go
  wren/compute/manager.go
  wren/compute/prepare.go
Labels: wren, sparrow

#291 Rewrite the "getting started" page
  docs-src/modules/getting-started/pages/index.adoc
Labels: documentation

#296 Revise Jupyter hello-world to align to the new getting-started and ju…
  docs-src/modules/ROOT/pages/installing.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Labels: documentation

#240 Updates Python Client to use file URI Prefix
  clients/python/src/kaskada/utils.py
  clients/python/tests/test_table.py
Labels: python

#307 Update pyproject.toml to 0.1.7
  clients/python/pyproject.toml
Labels: python

#304 Update Log Output Files (#274)
  clients/python/src/kaskada/api/api_utils.py
  clients/python/src/kaskada/api/session.py
  clients/python/tests/api/test_session.py
Labels: python

#315 (ci) adds S3 integration tests
  .github/workflows/ci_engine.yml
  Makefile
  tests/integration/shared/helpers/helpers.go
Labels: build

#313 Update Log Output Files Documentation (#274)
  docs-src/modules/troubleshooting/pages/logs.adoc
Labels: documentation

#329 create release v0.6.2
  Cargo.lock
  Cargo.toml
  wren/.version
Labels: wren, sparrow

#331 docs: cli echo path fix
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#332 docs: extra ` in CLI onboarding
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#333 docs: Kaskada CLI optional PATH
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#334 docs: execute command cli
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation

#328 updated cli getting started docs
  docs-src/modules/ROOT/pages/loading-data.adoc
  docs-src/modules/developing/pages/tables.adoc
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/getting-started/pages/hello-world-jupyter.adoc
Labels: documentation

#340 feat: add fenlmagic extension loaded message (#305)
  clients/python/src/fenlmagic/__init__.py
Labels: enhancement, python

#345 (docs) fix integrations menu
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
  docs-src/modules/integrating/nav.adoc
Labels: documentation

#348 update issue templates
  .github/ISSUE_TEMPLATE/doc_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: build

#323 draft: Fail Unsupported Columns (#318)
  crates/sparrow-main/src/serve/file_service.rs
  crates/sparrow-main/tests/e2e/parquet_tests.rs
  crates/sparrow-runtime/src/metadata/raw_metadata.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/prepare/error.rs
  wren/compute/manager.go
  wren/go.sum
  wren/service/table.go
Labels: wren, sparrow

#346 (ci) call apt-get update before installing qemu packages
  .github/workflows/release_engine.yml
Labels: build

#350 ignore no dataToken error
  wren/service/query_v1.go
Labels: wren

#351 (ci) use callable workflows for docs actions
  .github/workflows/publish-antora-docs.yml
Labels: documentation, build

#354 docs: Add GCP Configuration to Loading Data
  docs-src/modules/ROOT/pages/loading-data.adoc
Labels: documentation

#356 docs: update to include readthedocs for clients
  docs-src/modules/ROOT/pages/installing.adoc
  docs-src/modules/developing/nav.adoc
Labels: documentation

#298 api changes for long-lived materializations in sparrow
  crates/sparrow-api/src/kaskada/v1alpha.rs
  crates/sparrow-catalog/src/update/execute_example.rs
  crates/sparrow-compiler/src/compile.rs
  crates/sparrow-compiler/src/data_context.rs
  crates/sparrow-compiler/src/frontend/slice_analysis.rs
  crates/sparrow-compiler/tests/compiler_golden_tests.rs
  crates/sparrow-main/src/serve/compute_service.rs
  crates/sparrow-main/tests/e2e/basic_error_tests.rs
  crates/sparrow-main/tests/e2e/cast_tests.rs
  crates/sparrow-main/tests/e2e/decoration_tests.rs
  crates/sparrow-main/tests/e2e/entity_key_output_tests.rs
  crates/sparrow-main/tests/e2e/fixture/query_fixture.rs
  crates/sparrow-main/tests/e2e/fixtures.rs
  crates/sparrow-main/tests/e2e/json_tests.rs
  crates/sparrow-main/tests/e2e/lookup_tests.rs
  crates/sparrow-main/tests/e2e/multiple_tables.rs
  crates/sparrow-main/tests/e2e/notebooks/documentation_code_tests.rs
  crates/sparrow-main/tests/e2e/notebooks/event_data_tests.rs
  crates/sparrow-main/tests/e2e/notebooks/gaming_tests.rs
  crates/sparrow-main/tests/e2e/notebooks/sample_tests.rs
  crates/sparrow-main/tests/e2e/parquet_tests.rs
  crates/sparrow-main/tests/e2e/prepare_tests.rs
  crates/sparrow-main/tests/e2e/record_tests.rs
  crates/sparrow-main/tests/e2e/resumeable_tests.rs
  crates/sparrow-main/tests/e2e/shift_tests.rs
  crates/sparrow-main/tests/e2e/tick_tests.rs
  crates/sparrow-main/tests/e2e/when_tests.rs
  crates/sparrow-main/tests/e2e/windowed_aggregation_tests.rs
  crates/sparrow-main/tests/e2e/with_key_tests.rs
  crates/sparrow-runtime/src/execute/compute_executor.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/execute/progress_reporter.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/read/table_reader.rs
  crates/sparrow-runtime/src/s3/download_snapshot.rs
  crates/sparrow-runtime/src/s3/upload_snapshot.rs
  proto/kaskada/kaskada/v1alpha/common.proto
  proto/kaskada/kaskada/v1alpha/compute_service.proto
  wren/compute/manager.go
Labels: wren, sparrow, proto

#355 Update Default Data Location to User Directory Cache (#253)
  wren/client/ent_client.go
  wren/client/object_store_client.go
  wren/main.go
Labels: documentation, wren

#300 (ci) updates rust builds for PRs only to use bigger machines
  .github/workflows/reusable_ci_rust.yml
Labels: build

#357 cleaned up dockerfiles and added jupyter build
  .github/workflows/ci_engine.yml
  .github/workflows/release_engine.yml
  .github/workflows/reusable_ci_wren.yml
  Dockerfile.integration
  Dockerfile.jupyter
  Dockerfile.jupyter.dockerignore
  Dockerfile.notebook
  tests/integration/docker-compose-ci-integration.yml
Labels: build

#320 Add execution stream for pulsar
  Cargo.lock
  crates/sparrow-arrow/Cargo.toml
  crates/sparrow-arrow/src/avro.rs
  crates/sparrow-arrow/src/avro/avro_arrow.rs
  crates/sparrow-main/tests/e2e/fixture/local_table.rs
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/compute_executor.rs
  crates/sparrow-runtime/src/execute/operation.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/execute/operation/testing.rs
  crates/sparrow-runtime/src/execute/output/pulsar.rs
  crates/sparrow-runtime/src/lib.rs
  crates/sparrow-runtime/src/metadata/raw_metadata.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/prepare/column_behavior.rs
  crates/sparrow-runtime/src/prepare/execute_input_stream.rs
  crates/sparrow-runtime/src/prepare/prepare_input_stream.rs
  crates/sparrow-runtime/src/prepare/prepare_iter.rs
  crates/sparrow-runtime/src/prepare/prepare_metadata.rs
  crates/sparrow-runtime/src/prepare/slice_preparer.rs
  crates/sparrow-runtime/src/streams.rs
  crates/sparrow-runtime/src/streams/pulsar.rs
  crates/sparrow-runtime/src/streams/pulsar/schema.rs
  crates/sparrow-runtime/src/streams/pulsar/stream.rs
Labels: sparrow

#358 updated logging formats of both processes to be more similar
  Cargo.lock
  Cargo.toml
  clients/python/src/kaskada/api/session.py
  clients/python/tests/api/test_session.py
  crates/sparrow-main/src/snapshots/sparrow_main__tests__main_help_stdout.snap
  crates/sparrow-main/src/tracing_setup.rs
  crates/sparrow-main/src/tracing_setup/request_id_format.rs
  wren/main.go
  wren/telemetry/logging.go
Labels: python, wren, sparrow

#359 fix engine log startup
  clients/python/src/kaskada/api/session.py
  clients/python/tests/api/test_session.py
Labels: python

#363 bumped versions to 0.6.4
  Cargo.lock
  Cargo.toml
  wren/.version
Labels: wren, sparrow

#368 added interface for computeManger
  wren/compute/interface.go
  wren/compute/manager.go
  wren/main.go
  wren/service/materialization.go
  wren/service/query_v1.go
  wren/service/query_v2.go
  wren/service/table.go
  wren/service/view.go
Labels: wren

#370 added mock generation to wren
  .github/workflows/reusable_ci_wren.yml
  .gitignore
  Makefile
  wren/.mockery.yaml
  wren/README.md
  wren/service/analyzer_test.go
  wren/service/query_v1_test.go
Labels: wren, build

#376 Fenl Diagnostic HTML Rendering (#280)
  clients/python/src/kaskada/errors/__init__.py
  clients/python/src/kaskada/errors/error_codes.py
  clients/python/src/kaskada/formatters_shared.py
  clients/python/tests/errors/test_error_codes.py
  clients/python/tests/test_formatters_shared.py
  docs-src/modules/fenl/nav.adoc
  docs-src/modules/fenl/pages/fenl-diagnostic-codes.adoc
Labels: documentation, python

#288 docs: Update timelines notebook
  examples/timelines/.gitignore
  examples/timelines/kaskada_oss.ipynb
  examples/timelines/visualize.py
Labels: documentation

#366 feat: real-time streaming poc from cli
  crates/sparrow-api/src/kaskada/v1alpha.rs
  crates/sparrow-catalog/src/update/execute_example.rs
  crates/sparrow-main/src/batch.rs
  crates/sparrow-main/src/lib.rs
  crates/sparrow-main/src/main.rs
  crates/sparrow-main/src/materialize.rs
  crates/sparrow-main/src/prepare.rs
  crates/sparrow-main/src/script.rs
  crates/sparrow-main/src/serve/compute_service.rs
  crates/sparrow-main/src/snapshots/sparrow_main__tests__main_help_stdout.snap
  crates/sparrow-main/tests/e2e/fixture/query_fixture.rs
  crates/sparrow-runtime/src/data_manager.rs
  crates/sparrow-runtime/src/execute.rs
  crates/sparrow-runtime/src/execute/operation.rs
  crates/sparrow-runtime/src/execute/operation/scan.rs
  crates/sparrow-runtime/src/execute/operation/testing.rs
  crates/sparrow-runtime/src/execute/output.rs
  crates/sparrow-runtime/src/execute/output/object_store.rs
  crates/sparrow-runtime/src/execute/output/pulsar.rs
  crates/sparrow-runtime/src/lib.rs
  crates/sparrow-runtime/src/prepare.rs
  crates/sparrow-runtime/src/prepare/execute_input_stream.rs
  crates/sparrow-runtime/src/read.rs
  crates/sparrow-runtime/src/read/error.rs
  crates/sparrow-runtime/src/read/stream_reader.rs
  crates/sparrow-runtime/src/read/table_reader.rs
  crates/sparrow-runtime/src/streams/pulsar/schema.rs
  crates/sparrow-runtime/src/streams/pulsar/stream.rs
  examples/materialize_cli/README.md
  examples/materialize_cli/materialize_schema.yaml
  examples/materialize_cli/materialize_script.yaml
  examples/materialize_cli/messages/avro_schema_definition
  examples/materialize_cli/messages/msg1.avro
  examples/materialize_cli/messages/msg2.avro
  examples/materialize_cli/messages/msg3.avro
  examples/materialize_cli/pulsar_materialize_script.yaml
  examples/materialize_cli/topic_schema_definition
  wren/compute/query_context.go
Labels: enhancement, wren, sparrow

#382 (ci): fix typo in expression for skipping integ tests
  .github/workflows/ci_engine.yml
Labels: build

#386 refactored the compute package into several interfaces
  wren/.mockery.yaml
  wren/client/compute_clients.go
  wren/compute/compile_manager.go
  wren/compute/compile_manager_test.go
  wren/compute/compute_manager.go
  wren/compute/compute_suite_test.go
  wren/compute/file_manager.go
  wren/compute/helpers.go
  wren/compute/interface.go
  wren/compute/manager.go
  wren/compute/materialization_manager.go
  wren/compute/prepare_manager.go
  wren/compute/query_context.go
  wren/compute/query_result.go
  wren/go.mod
  wren/go.sum
  wren/main.go
  wren/service/materialization.go
  wren/service/query_v1.go
  wren/service/query_v2.go
  wren/service/table.go
  wren/service/view.go
Labels: wren

#389 example: Add SVG to PNG conversion script
  examples/timelines/.gitignore
  examples/timelines/convert.sh
Labels: cla-signed

#393 Update working-with-records.adoc
  docs-src/modules/fenl/pages/working-with-records.adoc
Labels: documentation, cla-signed

#396 doc: fix mac OSX xattr kaskada cli
  docs-src/modules/getting-started/pages/hello-world-cli.adoc
Labels: documentation, cla-signed

#395 feat: Remote Session Improvements (python)
  clients/python/src/fenlmagic/__init__.py
  clients/python/src/kaskada/api/remote_session/__init__.py
  clients/python/src/kaskada/api/session.py
  clients/python/src/kaskada/client.py
  docs-src/modules/tools-and-resources/nav.adoc
  docs-src/modules/tools-and-resources/pages/remote-session.adoc
Labels: documentation, enhancement, python, cla-signed

#398 ci(release): login and push release images to DockerHub
  .github/workflows/release_engine.yml
Labels: build, cla-signed

#402 bump versions for release
  Cargo.lock
  Cargo.toml
  clients/python/pyproject.toml
  wren/.version
Labels: python, wren, sparrow, cla-signed

#405 Use a relative path for the file, include a step allowing this to run…
  examples/ecommerce/Notebook.ipynb
Labels: cla-signed

#400 ci(integration tests): testing condition for integration tests
  .github/workflows/ci_engine.yml
Labels: build, cla-signed

#401 ci(cla check): workaround for making cla check required
  .github/workflows/ci_label_checker.yml
Labels: build, cla-signed

#399 build: Don't ignore `main`
  .gitignore
  Makefile
Labels: build, cla-signed

#406 docs(installation): note on permissions and pip
  docs-src/modules/ROOT/pages/installing.adoc
Labels: documentation, cla-signed
